<?php
/** phpcs:ignoreFile */

/** @var \OnitsukaTiger\Customer\Block\Widget\PersonalInformation $block */
?>

<!--
<div class="field choice agreement newsletter">
    <input type="checkbox" name="personal_information" title="" value="1" id="personal_information" class="checkbox">
    <label for="personal_information" class="label">
        <?= __("개인정보의 선택적 수집·이용에 동의합니다.")?>
        <a target="_blank" href="<?= $this->getUrl('privacy-policy-241114')?>">자세히보기</a>
    </label>
</div>
-->