<?php
/**
* @author OnitsukaTiger Team
* @copyright Copyright (c) 2022 OnitsukaTiger (https://www.onitsukatiger.com)
* @package Custom Checkout Fields for Magento 2
*/
?>
<?php
/** @var $block \OnitsukaTiger\OrderAttribute\Block\Adminhtml\Attribute\Edit\Tab\Options\Tooltip */
/** @var $escaper \Magento\Framework\Escaper */
?>
<fieldset class="fieldset-wrapper admin__collapsible-block-wrapper">
    <div class="fieldset-wrapper-title">
        <strong class="admin__collapsible-title"
                data-toggle="collapse"
                data-target="#manage-tooltip-panel"
                data-bs-toggle="collapse"
                data-bs-target="#manage-tooltip-panel">
            <span><?= $escaper->escapeHtml(__('Manage Tooltip')) ?></span>
        </strong>
    </div>
    <div class="fieldset-wrapper-content collapse" id="manage-tooltip-panel" style="height: 0px; display: none;">
        <table class="admin__control-table">
            <thead>
            <tr id="attribute-tooltip-options-table">
                <?php foreach ($block->getStores() as $store): ?>
                    <th><?= $escaper->escapeHtml(__($store->getName())) ?></th>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <tr class="col-draggable">
                <?php $tooltips = $block->getTooltipValues()?>
                <?php foreach ($block->getStores() as $store): ?>
                    <td class="col-store-view multi-input">
                        <input class="input-text"
                               name="store_tooltips[<?= /* @noEscape */ $store->getId() ?>]"
                               id="tooltip-strore-<?= /* @noEscape */ $store->getId() ?>"
                               type="text"
                               value="<?= $escaper->escapeHtml($tooltips[$store->getId()]) ?>">
                    </td>
                <?php endforeach; ?>
            </tr>
            </tbody>
        </table>
    </div>
</fieldset>
