<?php
// @codingStandardsIgnoreFile
?>
<?php
$_helper = $this->helper('WeltPixel\GA4\Helper\Data');
$_metaPixelHelper = $this->helper('WeltPixel\GA4\Helper\MetaPixelTracking');
$_bingPixelHelper = $this->helper('WeltPixel\GA4\Helper\BingPixelTracking');
$_klaviyoPixelHelper = $this->helper('WeltPixel\GA4\Helper\KlaviyoPixelTracking');
$_redditPixelHelper = $this->helper('WeltPixel\GA4\Helper\RedditPixelTracking');
$_tiktokPixelHelper = $this->helper('WeltPixel\GA4\Helper\TiktokPixelTracking');
$_xPixelHelper = $this->helper('WeltPixel\GA4\Helper\XPixelTracking');
$_pinterestPixelHelper = $this->helper('WeltPixel\GA4\Helper\PinterestPixelTracking');
$scriptAdditionalTag = $_helper->getScriptAttributes();
if ($_helper->isDevMoveJsBottomEnabled()) {
    $scriptAdditionalTag .= ' data-exclude-this-tag="text/x-magento-template" ';
}
$cspNonceProvider = $_helper->getCspNonceProvider();
if ($cspNonceProvider) {
    $scriptAdditionalTag .= ' nonce="'. $cspNonceProvider->generateNonce() .'"';
}
?>

<?php
if ($_helper->isEnabled()
    || $_bingPixelHelper->isBingPixelTrackingEnabled()
    || $_klaviyoPixelHelper->isKlaviyoPixelTrackingEnabled()
    || $_redditPixelHelper->isRedditPixelTrackingEnabled()
    || $_tiktokPixelHelper->isTiktokPixelTrackingEnabled()
    || $_xPixelHelper->isXPixelTrackingEnabled()
    || $_metaPixelHelper->isMetaPixelTrackingEnabled()
    || $_pinterestPixelHelper->isPinterestPixelTrackingEnabled()) :
    $isCookieRestrictionModeEnabled = $_helper->isCookieRestrictionModeEnabled() ?? 0;
    $currentWebsiteId = $_helper->getCurrentWebsiteId();
    $cookieName = \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE;
?>
<script<?= /* @noEscape */ $scriptAdditionalTag?>>
    window.getWpGA4Cookie = function(name) {
        match = document.cookie.match(new RegExp(name + '=([^;]+)'));
        if (match) return decodeURIComponent(match[1].replace(/\+/g, ' ')) ;
    };

    window.ga4AllowServices = false;

    var isCookieRestrictionModeEnabled = <?= /* @noEscape */ $isCookieRestrictionModeEnabled ?>,
        currentWebsiteId = <?= /* @noEscape */ $currentWebsiteId ?>,
        cookieRestrictionName = '<?= /* @noEscape */ $cookieName ?>';

    if (isCookieRestrictionModeEnabled) {
        allowedCookies = window.getWpGA4Cookie(cookieRestrictionName);

        if (allowedCookies !== undefined) {
            allowedWebsites = JSON.parse(allowedCookies);

            if (allowedWebsites[currentWebsiteId] === 1) {
                window.ga4AllowServices = true;
            }
        }
    } else {
        window.ga4AllowServices = true;
    }
</script>
<?php endif; ?>
