<?php
    $element = $block->getElement();
    $form = $element->getForm();
    /** @var \Magento\Config\Block\System\Config\Form $parentForm */
    $parentForm = $form->getParent();
    $fontsizeConfigVal = $parentForm->getConfigValue('barcode_section/barcode_group/fontsize');
?>

<div>
    <div id="fontsizeSlider"></div>
    <input type="hidden" 
        id="barcode_section_barcode_group_fontsize" 
        name="<?= $block->getFieldName() ?>"
        value="<?= $fontsizeConfigVal ?>">
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $("#fontsizeSlider").slider({
            range: "min",
            min: 8,
            max: 36,
            value: "<?= $fontsizeConfigVal ?>",
            slide: function( event, ui ) {
                $(this).find('.ui-slider-handle').text(ui.value);
                $("#barcode_section_barcode_group_fontsize").val(ui.value);
            },
            create: function(event, ui) {
                var v=$(this).slider('value');
                $(this).find('.ui-slider-handle').text(v);
                $("#barcode_section_barcode_group_fontsize").val(v);
            }
        });
    });
</script>