<?php
/** phpcs:ignoreFile */

namespace OnitsukaTigerKorea\ActionLog\Model\Export;

use Magento\Framework\Api\Search\DocumentInterface;
use Magento\Framework\Api\Search\SearchResultInterface;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\Convert\Excel;
use Magento\Framework\Convert\ExcelFactory;
use Magento\Framework\Exception\InputException;
use Magento\Framework\Filesystem;
use Magento\Ui\Component\MassAction\Filter;
use Magento\Ui\Model\Export\MetadataProvider;
use Magento\Ui\Model\Export\SearchResultIterator;
use Magento\Ui\Model\Export\SearchResultIteratorFactory;

class ConvertToXml extends \Magento\Ui\Model\Export\ConvertToXml
{
    /**
     * @var RequestInterface
     */
    protected $request;

    /**
     * @var string[]
     */
    protected $restrictExportGridData = [
        "sales_order_invoice_grid",
        "customer_listing",
        "sales_order_shipment_grid",
        "sales_order_creditmemo_grid"
    ];

    /**
     * @param Filesystem $filesystem
     * @param RequestInterface $request
     * @param Filter $filter
     * @param MetadataProvider $metadataProvider
     * @param ExcelFactory $excelFactory
     * @param SearchResultIteratorFactory $iteratorFactory
     * @throws \Magento\Framework\Exception\FileSystemException
     */
    public function __construct(
        Filesystem                  $filesystem,
        RequestInterface            $request,
        Filter                      $filter,
        MetadataProvider            $metadataProvider,
        ExcelFactory                $excelFactory,
        SearchResultIteratorFactory $iteratorFactory
    ) {
        $this->request = $request;
        parent::__construct($filesystem, $filter, $metadataProvider, $excelFactory, $iteratorFactory);
    }

    public function getXmlFile()
    {
        $namespace = $this->request->getParam('namespace');
        if (in_array($namespace, $this->restrictExportGridData)) {
            $component = $this->filter->getComponent();

            // md5() here is not for cryptographic use.
            // phpcs:ignore Magento2.Security.InsecureFunction
            $name = md5(microtime());
            $file = 'export/' . $component->getName() . $name . '.xml';

            $this->filter->prepareComponent($component);
            $this->filter->applySelectionOnTargetProvider();

            $component->getContext()->getDataProvider()->setLimit(0, 0);

            /** @var SearchResultInterface $searchResult */
            $searchResult = $component->getContext()->getDataProvider()->getSearchResult();

            /** @var DocumentInterface[] $searchResultItems */
            $searchResultItems = $searchResult->getItems();
            $newSearchResultItems = [];
            $this->prepareItem($component->getName(), $searchResultItems);
            $xmlItems = 0;
            $isKrItemsToExport = true;
            foreach ($searchResultItems as $searchResultItem) {
                if (($searchResultItem->getWebsiteId() && $searchResultItem->getWebsiteId() != "4") ||
                    ($searchResultItem->getStoreId() && $searchResultItem->getStoreId() != 5)) {
                    $newSearchResultItems[] = $searchResultItem;
                    $xmlItems++;
                    $isKrItemsToExport = false;
                }
            }

            if ($isKrItemsToExport) {
                throw new InputException(__($namespace));
            }

            /** @var SearchResultIterator $searchResultIterator */
            $searchResultIterator = $this->iteratorFactory->create(['items' => $newSearchResultItems]);

            /** @var Excel $excel */
            $excel = $this->excelFactory->create(
                [
                    'iterator' => $searchResultIterator,
                    'rowCallback' => [$this, 'getRowData'],
                ]
            );

            $this->directory->create('export');
            $stream = $this->directory->openFile($file, 'w+');
            $stream->lock();

            $excel->setDataHeader($this->metadataProvider->getHeaders($component));
            $excel->write($stream, $component->getName() . '.xml');

            $stream->unlock();
            $stream->close();
            if ($xmlItems > 0) {
                return [
                    'type' => 'filename',
                    'value' => $file,
                    'rm' => true  // can delete file after use
                ];
            }
            return [];
        }
        return parent::getXmlFile(); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $componentName
     * @param array $items
     * @return void
     */
    public function prepareItem($componentName, array $items = [])
    {
        foreach ($items as $document) {
            if ($document->getWebsiteId() != "4") {
                $this->metadataProvider->convertDate($document, $componentName);
            }
        }
    }
}
