<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\ConfigurableProduct\Model\Product\Type\Configurable;

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
/** @var $_order \Magento\Sales\Model\Order */
$_order = $_item->getOrder();

$catalogHelper = $this->helper(\Magento\Catalog\Helper\Image::class);

$helperReturn = $this->helper(\OnitsukaTiger\Rma\Helper\Data::class);
$productForThumbnail = $helperReturn->getFinalProductThumbnail($_item, $_order);

/** @var \Vaimo\OTScene7Integration\Helper\Data $scene7Helper */
$scene7Helper = $this->helper(\Vaimo\OTScene7Integration\Helper\Data::class);
$image_url = $scene7Helper->getOrderItemProductImage($productForThumbnail, "order_item_image_size");
?>
<?php $helperFixture = $this->helper(\OnitsukaTiger\Fixture\Helper\Data::class);?>
<tr>
    <td class="item-info">
        <p>
            <img border="0" src="<?= $image_url ?>" alt="<?= $block->escapeHtml($_item->getName()) ?>"/>
        </p>
    </td>
    <td class="item-name">
        <div class="product-information">
            <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
            <p class="sku"><?= $block->escapeHtml(__('Style')) ?> #: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
            <?php if ($block->getItemOptions()) : ?>
                <div class="product-options">
                    <ul>
                        <?php foreach ($block->getItemOptions() as $_option) : ?>
                            <li>
                                <?= $block->escapeHtml($_option['label']) ?> : <?= /* @noEscape */ nl2br($block->escapeHtml($_option['print_value'] ?? $_option['value'])) ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
        </div>
    </td>
    <td class="item-qty"><?= (float) $_item->getQtyOrdered() ?></td>
    <td class="item-price" style=" border-right: 1px solid #000000;">
        <?php if((int)$helperFixture->getConfig('tax/cart_display/subtotal') == 1):?>
            <?= /* @noEscape */ $_order->formatPrice($_item->getPrice()) ?>
        <?php else: ?>
            <?= /* @noEscape */ $_order->formatPrice($_item->getPriceInclTax()) ?>
        <?php endif;?>
    </td>
</tr>
