<?php

namespace OnitsukaTigerCpss\Pos\Cron;

use Cpss\Crm\Model\ShopReceiptFactory;
use Cpss\Pos\Helper\CreateCsv;
use Cpss\Pos\Helper\Data;
use Cpss\Pos\Helper\Mail;
use Cpss\Pos\Logger\CsvLogger;
use Cpss\Pos\Logger\Logger;
use Cpss\Pos\Model\PosDataFactory;
use Cpss\Pos\Model\ResourceModel\PosData;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\App\ResourceConnection;
use Magento\Framework\Encryption\EncryptorInterface;
use Magento\Framework\Filesystem\Io\Sftp;
use Magento\Framework\Stdlib\DateTime\TimezoneInterface;
use phpseclib3\Crypt\PublicKeyLoader;
use Magento\Store\Model\ScopeInterface;
use OnitsukaTigerCpss\Pos\Helper\HelperData;
class UpdatePosData extends \Cpss\Pos\Cron\UpdatePosData
{
    protected $helper;
    /**
     * @param ResourceConnection $resourceConnection
     * @param Sftp $sftp
     * @param ScopeConfigInterface $scopeConfig
     * @param Logger $logger
     * @param ShopReceiptFactory $shopReceipt
     * @param EncryptorInterface $encryptor
     * @param CreateCsv $createCpssCsv
     * @param PosDataFactory $posdataFactory
     * @param PosData $posdataRessourceModel
     * @param TimezoneInterface $timezone
     * @param CsvLogger $csvLogger
     * @param Data $posHelper
     * @param Mail $posMailer
     */
    public function __construct(
        ResourceConnection   $resourceConnection,
        Sftp                 $sftp,
        ScopeConfigInterface $scopeConfig,
        Logger               $logger,
        ShopReceiptFactory   $shopReceipt,
        EncryptorInterface   $encryptor,
        CreateCsv            $createCpssCsv,
        PosDataFactory       $posdataFactory,
        PosData              $posdataRessourceModel,
        TimezoneInterface    $timezone,
        CsvLogger            $csvLogger,
        Data                 $posHelper,
        Mail                 $posMailer,
        \Magento\Framework\Filesystem\DirectoryList $directoryList,
        \Magento\Framework\Filesystem\Driver\File $driverFile,
        \OnitsukaTigerCpss\Crm\Helper\HelperData $helperData,
        \OnitsukaTigerCpss\PaymentList\Model\Source\PaymentOptions $paymentOptions
    )
    {
        parent::__construct($resourceConnection,
            $sftp,
            $scopeConfig,
            $logger,
            $shopReceipt,
            $encryptor,
            $createCpssCsv,
            $posdataFactory,
            $posdataRessourceModel,
            $timezone,
            $csvLogger,
            $posHelper,
            $posMailer,
            $directoryList,
            $driverFile,
            $helperData,
            $paymentOptions);

    }

    /**
     * @return void
     */
    public function execute($storeCode)
    {
        if (!$this->helperData->isCpssModuleEnable()) {
            return;
        }
        parent::execute($storeCode); // TODO: Change the autogenerated stub
    }

    /**
     * Get Config Value in Admin
     *
     * @param string ("host","username","password","port","path") $path
     * @return string
     */
    public function getConfigValue($path,$scope = null)
    {
        if ($path == 'port') {
            if (!$this->scopeConfig->getValue(self::XML_PATH . $path,ScopeInterface::SCOPE_STORE, $scope)) {
                return self::DEFAULT_SFTP_PORT;
            }
        }
        return $this->scopeConfig->getValue(self::XML_PATH . $path,ScopeInterface::SCOPE_STORE, $scope);
    }
    /**
     * Connect to sftp
     *
     * param bool $userStandByServer
     * @return bool
     */
    public function connectSftp($useStandByServer = false)
    {
        try {
            if ($useStandByServer) {
                $auth = [
                    'host' => $this->getConfigValue("standby_host"),
                    'port' => $this->getConfigValue("standby_port"),
                    'username' => $this->getConfigValue("username")
                ];
            } else {
                $auth = [
                    'host' => $this->getConfigValue("host"),
                    'port' => $this->getConfigValue("port"),
                    'username' => $this->getConfigValue("username")
                ];
            }

            //Set sftp port (need to append to host using ':' )
            if (isset($auth['port']) && $auth['port'] != 22) {
                $auth['host'] .= ':' . $auth['port'];
            }

            $this->usedSftpHost = $auth["host"];
            $this->logger->info("SFTP AUTH", $auth);
            $methodAccess = $this->getConfigValue("method_access");

            if ($methodAccess == "key") {
                $key = $this->encryptor->decrypt($this->getConfigValue("private_key"));
                $rsa = PublicKeyLoader::load($key);
                $auth['password'] = $rsa;
            } else {
                $auth['password'] = $this->getConfigValue("password");
            }

            $this->sftp->open($auth);
            return true;
        } catch (\Exception $e) {
            $this->logger->critical($e->getMessage());
            return false;
        }
    }

    /**
     * @param $purchaseId
     * @return \Magento\Framework\Phrase|true
     */
    public function validatePurchaseIdFormat($purchaseId, $storeCode = '')
    {
        $breakDown = explode("_", $purchaseId);
        $count = count($breakDown);
        if ($count <> 4) {
            return __('%1 Invalid purchaseId format: Purchase date (8 digits)_Store ID (5 digits)_POS register terminal No. (4 digits)_Receipt number (8 digits)', $purchaseId);
        }

        if (!$this->dateFormat($breakDown[0])) {
            return __('%1 Invalid Date format: YYYYMMDD', $breakDown[0]);
        }
        if (!empty($storeCode) && $storeCode == 'kr') {
            if (strlen($breakDown[1]) <> 8 || strlen($breakDown[2]) <> 5 || strlen($breakDown[3]) <> 10) {
                return __('%1 Invalid purchaseId section length: Purchase date (8 digits)_Store ID (5 digits)_POS register terminal No. (4 digits)_Receipt number (8 digits)', $purchaseId);
            }
        } else {
            if (strlen($breakDown[1]) <> 6 || strlen($breakDown[2]) <> 5 || strlen($breakDown[3]) <> 10) {
                return __('%1 Invalid purchaseId section length: Purchase date (8 digits)_Store ID (5 digits)_POS register terminal No. (4 digits)_Receipt number (8 digits)', $purchaseId);
            }
        }

        return true;
    }
}
