<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// @codingStandardsIgnoreFile
/** @var $block \OnitsukaTiger\EmailToWareHouse\Block\Order\Info */
$shipment = $block->getShipment();

/** @var $helperEmailToWareHouse \OnitsukaTiger\EmailToWareHouse\Helper\Data*/
$helperEmailToWareHouse = $this->helper(\OnitsukaTiger\EmailToWareHouse\Helper\Data::class);
$avatarImage = $helperEmailToWareHouse->getMediaFromUrl('OnitsukaTiger_EmailToWareHouse::images/avatar.png');
$telephoneImage = $helperEmailToWareHouse->getMediaFromUrl('OnitsukaTiger_EmailToWareHouse::images/telephone.png');
$mapImage = $helperEmailToWareHouse->getMediaFromUrl('OnitsukaTiger_EmailToWareHouse::images/map.png');
$orderId = $shipment->getOrder()->getIncrementId();
$helper = $this->helper(\OnitsukaTiger\Store\Helper\Data::class);
$allowedStoreForDisplayOrderNo = [1, 2, 3, 4];
?>

<div class="row my-30">
    <table class="table-info">
        <tr class="border-top border-bottom">
            <td><h4>FROM ( SENDER )</h4></td>
            <td><h4>TO ( ADDRESSEE )</h4></td>
        </tr>
        <tr>
            <td>
                <div class="icon"><img class="avatar" src="<?= $avatarImage ?>"></div>
                <div class="info"><?= $block->escapeHtml($helper->removeSpecialCharacter($block->getWarehouseName($shipment))) ?></div>
                <div class="clear"></div>
            </td>
            <td>
                <div class="icon"><img class="avatar" src="<?= $avatarImage ?>"></div>
                <div class="info"><?= $block->escapeHtml($helper->removeSpecialCharacter($block->getToName($shipment))) ?></div>
                <div class="clear"></div>
            </td>
        </tr>
        <tr class="contact">
            <td>
                <?php if (!empty($block->getWarehousePhone($shipment))) : ?>
                    <div class="icon"><img class="phone" src="<?= $telephoneImage ?>"></div>
                    <div class="info"><?= $block->escapeHtml($helper->removeSpecialCharacter($block->getWarehousePhone($shipment))) ?></div>
                    <div class="clear"></div>
                <?php endif; ?>
            </td>
            <td>
                <div class="icon"><img class="phone" src="<?= $telephoneImage ?>"></div>
                <div class="info"><?= $block->escapeHtml($block->getToPhone($shipment)) ?></div>
                <div class="clear"></div>
            </td>
        </tr>
        <tr class="border-bottom address">
            <td>
                <div class="icon"><img class="map" src="<?= $mapImage ?>"></div>
                <div class="info"><?= $block->escapeHtml($block->getDetailWarehouseAddress($shipment)) ?></div>
                <div class="clear"></div>
            </td>
            <td>
                <div class="icon"><img class="map" src="<?= $mapImage ?>"></div>
                <div class="info"><?= $block->escapeHtml($helper->removeSpecialCharacter($block->getDetailShippingAddress($shipment))) ?></div>
                <div class="order-info"><strong>Order ID</strong><span><?= $block->escapeHtml($orderId) ?></span></div>
                <div class="clear"></div>
            </td>
        </tr>
    </table>
</div>

<div class="row">
    <div class="col">
        <div class="box">
            <h4 class="box-heading">Comments</h4>
            <div class="box-content comment">
                <div class="info">
                    <div class="order-number">
                        <?php if (in_array($shipment->getStoreId(), $allowedStoreForDisplayOrderNo)) { ?>
                            <span>Order No. <?= $orderId ?></span>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
