<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrder(); ?>
<?php $product = $block->getViewModel()->getProduct($_item->getSku()); ?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if($product):?>
        <p class="sku"><?= $product->getSkuWms()?></p>
        <?php endif; ?>
        <?php if ($block->getItemOptions()) : ?>
            <dl>
                <?php foreach ($block->getItemOptions() as $option) : ?>
                    <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                    <dd>
                        <?= /* @noEscape */  nl2br($block->escapeHtml($option['value'])) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= (float) $_item->getQty() ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $block->getItemPrice($_item->getOrderItem()) ?>
    </td>
</tr>
