<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter">
    <div class="top-newsletter">
        <p><?= $block->escapeHtml(__('NEWSLETTER')) ?></p>
    </div>
    <div class="content">
        <form class="form subscribe"
              action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              id="newsletter-validate-detail">
            <input type="hidden" name="isAjax" value="1"/>
            <div class="message-subscriber"><?= __('Please use a valid email address')?></div>
            <div class="form-container">
                <div class="field newsletter">
                    <div class="control">
                        <label for="newsletter">
                            <input name="email" type="email" id="newsletter"
                                   placeholder="<?= $block->escapeHtmlAttr(__('E-mail Address')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'
                            />
                        </label>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary"
                            title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                            type="submit"
                            aria-label="Subscribe">
                        <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                    </button>
                </div>
            </div>
            <label id="policy-checkbox" class="policy-checkbox">
                <input type="checkbox" checked="checked">
                <span class="checkmark"></span>
            </label>
            <div class="text-newsletter"><?= $block->getChildHtml('block_content_text_newsletter') ?></div>
        </form>
    </div>
    <script type="text/javascript">
        require.config({
            map: {
                '*': {
                    newsletterAjax: 'Magento_Newsletter/js/newsletter-ajax'
                }
            }
        });
    </script>
    <script type="text/x-magento-init">
        {
            "#newsletter-validate-detail": {
                "newsletterAjax": {
                    "isFooter": "1"
                }
            }
        }
    </script>
</div>
<div class="loadding-ajax newsletter-loading hidden">
    <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
</div>

