<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrder(); ?>
<?php $helperData = $this->helper(OnitsukaTigerKorea\ConfigurableProduct\Helper\Data::class); ?>

<?php
$productHelperData = $this->helper(\OnitsukaTiger\Catalog\Helper\Data::class);
$product = $productHelperData->getProduct($_item->getSku());
$color = $product->getResource()->getAttribute('color');
$colorValue = $color->getSource()->getOptionText($product->getData('color'));
?>
<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()) : ?>
            <dl>
                <?php foreach ($block->getItemOptions() as $option) : ?>
                    <dt><strong><em><?= $block->escapeHtml(__($option['label'])) ?></em></strong></dt>
                    <?php $sizeForDisplay = $helperData->getSizeForDisplay($_item->getSku(), $_item->getStoreId()) ?>
                    <?php if ($sizeForDisplay && strtolower($option['label']) == 'size') : ?>
                        <dd>
                            <?= /* @noEscape */
                            nl2br($block->escapeHtml($sizeForDisplay)) ?>
                        </dd>
                    <?php elseif ($colorValue && strtolower($option['label']) == 'colors') : ?>
                        <dd>
                            <?= /* @noEscape */
                            nl2br($block->escapeHtml($colorValue)) ?>
                        </dd>
                    <?php else: ?>
                        <dd>
                            <?= /* @noEscape */
                            nl2br($block->escapeHtml($option['value'])) ?>
                        </dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= (float)$_item->getQty() ?></td>
    <td class="item-price">
        <?= /* @noEscape */
        $block->getItemPrice($_item->getOrderItem()) ?>
    </td>
</tr>
