<?php
// @codingStandardsIgnoreFile
/** @var $block \WeltPixel\GA4\Block\BingPixel\Common */

/** @var \WeltPixel\GA4\Helper\BingPixelTracking $bingPixelHelper */
$bingPixelHelper = $this->helper('WeltPixel\GA4\Helper\BingPixelTracking');
$cspNonceProvider = $bingPixelHelper->getCspNonceProvider();
?>
<script <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
    let bingBeginCheckoutEventId = <?= /* @noEscape */ $bingPixelHelper->getJsEventIdGenerator() ?>;
</script>
<?php if ($bingPixelHelper->isBingPixelTrackingEnabled() && $bingPixelHelper->shouldBingPixelEventBeTracked(\WeltPixel\GA4\Model\Config\Source\BingPixel\TrackingEvents::EVENT_BEGIN_CHECKOUT)) :
?>
<script <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
        if (window.ga4AllowServices) {
            window.uetq = window.uetq || [];
            window.uetq.push('event', 'begin_checkout', {
                ecomm_pagetype: 'cart',
                ecomm_prodid: [<?= /* @noEscape */ $block->getCheckoutContentIds() ?>],
                ecomm_totalvalue: <?= /* @noEscape */ $block->getCheckoutValue() ?>,
                currency: "<?= /* @noEscape */ $bingPixelHelper->getCurrencyCode() ?>",
                items: <?= /* @noEscape */ $block->getCheckoutContents() ?>,
                custom_parameters: {
                    mid: bingBeginCheckoutEventId
                },
                mid: bingBeginCheckoutEventId
            });
    }
</script>
<?php endif; ?>

<?php if ($bingPixelHelper->isServerSideTrackingEnabled() && $bingPixelHelper->shouldBingServerSideEventBeTracked(\WeltPixel\GA4\Model\Config\Source\BingPixel\TrackingEvents::EVENT_BEGIN_CHECKOUT)) : ?>
    <script  <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
        requirejs(['jquery'],
            function  ($) {
                $(document).ready(function() {
                    var requestUrl = '<?php echo $block->escapeUrl($bingPixelHelper->getBingSSTrackUrl()); ?>';
                    $.post({
                        url: requestUrl,
                        global: false,
                        data: {
                            'eventId': bingBeginCheckoutEventId,
                            'eventName': 'BeginCheckout',
                            'eventIdentifier': '<?= /* @noEscape */ \WeltPixel\GA4\Model\Config\Source\BingPixel\TrackingEvents::EVENT_BEGIN_CHECKOUT  ?>',
                            'eventUrl': '<?= $block->escapeUrl($bingPixelHelper->getStoreCurrenUrl()) ?>',
                            'quoteId':'<?=  /* @noEscape */ $block->getQuoteId() ?>'
                        }
                    });
                });
            });
    </script>
<?php endif; ?>

