<?php
// @codingStandardsIgnoreFile
/** @var $block \WeltPixel\GA4\Block\BingPixel\Common */

/** @var \WeltPixel\GA4\Helper\BingPixelTracking $bingPixelHelper */
$bingPixelHelper = $this->helper('WeltPixel\GA4\Helper\BingPixelTracking');
$cspNonceProvider = $bingPixelHelper->getCspNonceProvider();
?>
<?php if ($bingPixelHelper->isBingPixelTrackingEnabled()) : ?>
    <script <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
        require(['jquery', 'Magento_Customer/js/customer-data'],
            function ($, customerData) {
                if (window.ga4AllowServices) {
                    $(document).ajaxComplete(function (event, xhr, settings) {
                        if (settings.url.search('/customer\/section\/load/') > 0) {
                            var response = xhr.responseJSON;
                            if (response.wp_ga4) {
                                var bingPixel = $.parseJSON(response.wp_ga4.bingpixel);
                                window.uetq = window.uetq || [];
                                for (index in bingPixel) {
                                    window.uetq.push(bingPixel[index].event, bingPixel[index].eventName, bingPixel[index].eventData);
                                }
                            }
                        }
                    });
                }
            });
    </script>
<?php endif; ?>
