<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var  $block \OnitsukaTiger\OrderTracking\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$catalogHelper = $this->helper(\Magento\Catalog\Helper\Image::class);
$scene7Helper = $this->helper(\Vaimo\OTScene7Integration\Helper\Data::class);
$product = $_item->getProduct();
$image_url = $scene7Helper->getOrderItemProductImage($product) ??
    $catalogHelper->init($product, 'product_page_image_small')
        ->setImageFile($product->getImage())->resize(80, 80)->getUrl();
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>">
        <img src="<?= $image_url?>" alt="<?= $block->escapeHtml($_item->getName()) ?>"/>
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
    </td>

    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Total Qty')) ?>">
        <span class="content"><?= (float) $block->getItem()->getQtyOrdered() ?></span>
    </td>

    <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Shipped Qty')) ?>">
        <span class="content"><?= (float) $block->getItem()->getQtyShipped() ?></span>
    </td>

    <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Item Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>

    <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>

    <td class="col status" data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>">
        <div class="order-status">
            <div class="status <?= $block->escapeHtml(strtolower($_item->getOrder()->getStatusLabel())) ?>">
                <span></span>
            </div>
        </div>
    </td>

    <td class="col logistic" data-th="<?= $block->escapeHtmlAttr(__('Logistic')) ?>">
        <span class="logistic">
            <?= /* @noEscape */ explode(' - ',$block->getOrder()->getShippingDescription())[0] ?>
        </span>
        <?php foreach ($block->getOrder()->getTracksCollection() as $track): ?>
            <p><strong><?= __('AWB No.:')?></strong> <a href="#"><?= $track->getTrackNumber()?></a></p>
        <?php endforeach;?>
    </td>
</tr>
