<?php
/** @var $block \OnitsukaTiger\CategoryModelImage\Block\Adminhtml\Product\Helper\Form\Gallery\Content */
$elementName = $block->getElement()->getName() . '[images]';
$formName = $block->getFormName();
$helper = $this->helper('OnitsukaTiger\CategoryModelImage\Helper\Data');
?>
<div id="<?= /* @noEscape */ $block->getHtmlId() ?>"
     class="gallery"
     data-mage-init='{"categoriesGallery":{"template":"#<?= /* @noEscape */ $block->getHtmlId() ?>-template"}}'
     data-parent-component="<?= $block->escapeHtmlAttr($block->getData('config/parentComponent')) ?>"
     data-images="<?= $block->escapeHtmlAttr($block->getImagesJson()) ?>"
     data-types="" data-position="<?= $helper->getLimitConfigution($block->getStoreViewId())?>"
>
    <?php if (!$block->getElement()->getReadonly()) {?>
        <div class="image image-placeholder">
            <?= $block->getUploaderHtml() ?>
            <div class="product-image-wrapper">
                <p class="image-placeholder-text">
                    <?= $block->escapeHtml(__('Browse to find image here')) ?>
                </p>
            </div>
        </div>
    <?php } ?>
    <script id="<?= /* @noEscape */ $block->getHtmlId() ?>-template" type="text/x-magento-template">
        <div class="image item<% if (data.disabled == 1) { %> hidden-for-front<% } %>"
             data-role="image">
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][position]"
                   value="<%- data.position %>"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   class="position"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][file]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="<%- data.file %>"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][link]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="<%- data.links %>"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][label]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="<%- data.label %>"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][status]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="<%- data.status %>"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][media_type]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="image"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][removed]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value=""
                   class="is-removed"/>
            <input id="positions-image-field" type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][positions]"
                   value="<%- data.positions %>"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][entity_id]"
                   value="<%- data.entity_id %>"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][link]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="<%- data.link %>"/>
            <input type="hidden"
                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][disabled]"
                   data-form-part="<?= $block->escapeHtmlAttr($formName) ?>"
                   value="<%- data.disabled %>"/>
            <div class="product-image-wrapper">
                <img class="product-image"
                     data-role="image-element"
                     src="<%- data.url %>"
                     alt="<%- data.label %>"/>

                <div class="actions">
                    <button type="button"
                            class="action-remove"
                            data-role="delete-button"
                            title="<?= $block->escapeHtmlAttr(__('Delete image')) ?>">
                    <span>
                        <?= $block->escapeHtml(__('Delete image')) ?>
                    </span>
                    </button>
                    <div class="draggable-handle"></div>
                </div>
                <div class="image-fade"><span><?= $block->escapeHtml(__('Disabled')) ?></span></div>
            </div>


            <div class="item-description">
                <div class="item-title" data-role="img-title"><%- data.label %></div>
                <div class="item-title" data-role="img-positions">Position : <%- data.positions %></div>
                <div class="item-size">
                    <span data-role="image-dimens"></span>, <span data-role="image-size"><%- data.sizeLabel %></span>
                </div>
            </div>
        </div>
    </script>

    <script data-role="img-dialog-container-tmpl" type="text/x-magento-template">
        <div class="image-panel" data-role="dialog">
        </div>
    </script>

    <script data-role="img-dialog-tmpl" type="text/x-magento-template">
        <div class="image-panel-preview">
            <img src="<%- data.url %>" alt="<%- data.label %>" />
        </div>
        <div class="image-panel-controls">
            <fieldset class="admin__fieldset fieldset-image-panel">
                <div class="admin__field field-image-description">
                    <label class="admin__field-label" for="image-description">
                        <span><?= $block->escapeHtml(__('Alt Text')) ?></span>
                    </label>

                    <div class="admin__field-control">
                        <textarea data-role="image-description"
                              rows="3"
                              class="admin__control-textarea"
                              name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][label]"><%- data.label %></textarea>
                      </div>
                </div>
                <div class="admin__field field-image-position">
                    <label class="admin__field-label" for="image-position">
                        <span><?= $block->escapeHtml(__('Position')) ?></span>
                    </label>

                    <div class="admin__field-control">
                        <input class="admin__control-text position-image"  data-image="positions" type="text" data-role="image-description" value="<%- data.positions %>" name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][positions]">
                        <label class="admin__field-error" style="display: none"><?= __('Please enter a valid number in this field.')?></label>
                        <label class="admin__field-error" style="display: none"><?= __('Please enter a number great than 0 in this field.')?></label>
                        <label class="admin__field-error" style="display: none"><?= __('The position exists. Please change a number in this field')?></label>
                        <p class="note" style="font-size: 10px">
                            <span>
                                <br/>
                                <?= __('Should be number and less than Product Per Page')?>
                                <br/>
                                <?= __('Auto Hidden if left value or great than Product Per Page')?>
                            </span>
                        </p>
                    </div>
                </div>
                <div class="admin__field field-image-links">
                    <label class="admin__field-label" for="image-links">
                        <span><?= $block->escapeHtml(__('Links')) ?></span>
                    </label>

                    <div class="admin__field-control">
                        <input class="admin__control-text" data-image="link"  type="text" data-role="image-description" value="<%- data.link %>" name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][link]">
                    </div>
                </div>
                <div class="admin__field field-image-Status">
                    <label class="admin__field-label" for="image-Status">
                        <span><?= $block->escapeHtml(__('Disable')) ?></span>
                    </label>

                    <div class="admin__field-control">
                        <div class="admin__actions-switch" data-role="switcher">
                            <input data-role="image-description"
                                   type="checkbox"
                                   data-image="status"
                                   class="admin__actions-switch-checkbox"
                                   id="<%- data.file_id %>"
                                   name="<?= $block->escapeHtmlAttr($elementName) ?>[<%- data.file_id %>][disabled]"
                                   value="1"
                            <% if (data.disabled == 1) { %>checked="checked"<% } %> />
                            <label class="admin__actions-switch-label" for="<%- data.file_id %>">
                                <span class="admin__actions-switch-text" data-bind="attr: {'data-text-on': toggleLabels.on, 'data-text-off': toggleLabels.off}" data-text-on="Yes" data-text-off="No"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="admin__field admin__field-inline field-image-size" data-role="size">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Image Size')) ?></span>
                    </label>
                    <div class="admin__field-value" data-message="<?= $block->escapeHtmlAttr(__('{size}')) ?>"></div>
                </div>

                <div class="admin__field admin__field-inline field-image-resolution" data-role="resolution">
                    <label class="admin__field-label">
                        <span><?= $block->escapeHtml(__('Image Resolution')) ?></span>
                    </label>
                    <div class="admin__field-value" data-message="<?= $block->escapeHtmlAttr(__('{width}^{height} px')) ?>"></div>
                </div>
            </fieldset>
        </div>
    </script>
</div>
<script>
    jQuery('body').trigger('contentUpdated');
</script>
