<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="block newsletter">
    <div class="top-newsletter">
        <?= $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('newsletter-message-information')
            ->toHtml();?>
    </div>
    <div class="content">
        <form class="form subscribe"
              action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              id="newsletter-validate-detail">
            <input type="hidden" name="isAjax" value="1"/>
            <div class="message-subscriber"><?= __('Please use a valid email address')?></div>
            <div class="form-container">
                <div class="field newsletter">
                    <div class="control">
                        <label for="newsletter">
                            <input name="email" oninvalid="setCustomValidity('이메일 아드레스에 \'@\' 를 포함하십시오.（例：johndoe@domain.com）')" type="email" id="newsletter"
                                   placeholder="<?= $block->escapeHtmlAttr(__('E-mail Address')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'
                            />
                        </label>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary"
                            title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                            type="submit"
                            aria-label="Subscribe">
                        <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                    </button>
                </div>
            </div>
            <label id="policy-checkbox" class="policy-checkbox">
                <input type="checkbox" checked="checked">
            </label>
            <p class="text-newsletter"><?= $block->escapeHtml(__("If you agree to receive the newsletter, you will be the first to receive information about new products, various benefits and promotions.")) ?></p>
            <p class="text-newsletter" style="margin-top: 0"><?= $block->escapeHtml(__("Read and agree to the <a href='%1'>Privacy Policy</a>, then click the button.", $block->getUrl('privacy-policy')), ['a']) ?></p>
        </form>
    </div>
    <script type="text/javascript">
        require.config({
            map: {
                '*': {
                    newsletterAjax: 'Magento_Newsletter/js/newsletter-ajax'
                }
            }
        });
    </script>
    <script type="text/x-magento-init">
        {
            "#newsletter-validate-detail": {
                "newsletterAjax": {
                    "isFooter": "1"
                }
            }
        }
    </script>
</div>
<div class="loadding-ajax newsletter-loading hidden">
    <div class="lds-spinner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
</div>

<div class="custome-popup custome-popup-off" style="display: none;">
    <div class="custome-modals-overlay-design">
        <div class="custome-popup-content">
            <button class="action-close" data-role="closeBtn" type="button">
            </button>
            <?= $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('newsletter-off-content')
                ->toHtml();
            ?>
            <div class="primary">
                <button type="button" id="save-newsletter-off" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"
                        class="action save primary">
                    <span>
                        <?= $block->escapeHtml(__('확인')) ?>
                    </span>
                </button>
            </div>
        </div>
    </div>
</div>



<div class="custome-popup custome-popup-on" style="display: none;">
    <div class="custome-modals-overlay-design">
        <div class="custome-popup-content">
            <button class="action-close" data-role="closeBtn" type="button">
            </button>
            <?= $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('newsletter-on-content')
                ->toHtml();
            ?>
            <div class="primary">
                <button type="button" id="save-newsletter-on" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"
                        class="action save primary">
                    <span><?= $block->escapeHtml(__('확인')) ?></span>
                </button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(".custome-popup .action-close").click(function () {
            $(".custome-popup").hide();
        });
        $('#newsletter-save').click(function () {
            var option_value_subscribed = document.getElementById("is_subscribed").value;
            if (option_value_subscribed == "") {
                $('.custome-popup-on').hide();
                $('.custome-popup-off').show();
            }
            if (option_value_subscribed == "1") {
                $('.custome-popup-on').show();
            }
        });

        $('#save-newsletter-on').click(function () {
            $('form#form-validate').submit();
        });
        $('#save-newsletter-off').click(function () {
            $('form#form-validate').submit();
        });

    });
</script>

