<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\ConfigurableProduct\Model\Product\Type\Configurable;

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $block->getOrder();

$catalogHelper = $this->helper(\Magento\Catalog\Helper\Image::class);
$helperReturn = $this->helper(\OnitsukaTiger\Rma\Helper\Data::class);

$productForThumbnail = $helperReturn->getFinalProductThumbnail($_item, $_order);
/** @var \Vaimo\OTScene7Integration\Helper\Data $scene7Helper */
$scene7Helper = $this->helper(\Vaimo\OTScene7Integration\Helper\Data::class);
$image_url = $scene7Helper->getOrderItemProductImage($productForThumbnail);

?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="item-info">
        <a href="<?= $_item->getProduct()? $_item->getProduct()->getProductUrl() :'#'?>"><img src="<?= $image_url?>" alt="<?= $block->escapeHtml($_item->getName()) ?>"/></a>
    </td>
    <td class="col name">
        <div class="item-description-content">
            <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        </div>
        <div class="item-details-container">
            <div class="item-qty">
                <label><?= $block->escapeHtml(__('Quantity:')) ?></label>
                <span><?= (int) $block->getItem()->getQtyOrdered() ?></span>
            </div>
            <div class="unit-price">
                <label><?= $block->escapeHtml(__('Unit Price:')) ?></label>
                <span><?= $block->getItemPriceHtml() ?></span>
            </div>
            <div class="sub-total">
                <label><?= $block->escapeHtml(__('Sub Total:')) ?></label>
                <span><?= $block->getItemRowTotalHtml() ?></span>
            </div>
        </div>
    </td>
    <td class="col actions">
        <?php if ($helperReturn->checkButtonReorder($_item->getOrder())): ?>
            <a href="#" data-role="order-return" class="reorder-btn btnReorder" data-return="<?= /* @noEscape */$helperReturn->getCreateReturnUrl($_item->getOrder(), $_item) ?>" class="action order">
                <span><?= $block->escapeHtml(__('Return')) ?></span>
            </a>
            <br/>
        <?php endif; ?>
    </td>
</tr>
