<form action="<?= $block->getUrl();?>rest/V1/updateMemberInfo" method="post" enctype="multipart/form-data">
    <input type="hidden" name="siteId" value="2289" />
    <input type="hidden" name="accessToken" value="hahah2289" />
    <input type="hidden" name="memberId" value="1" />
    <input type="text" name="email" value="jirenzhambre+20220322@gmail.com" />
    <input type="password" name="password" value="User2022" />
    <input type="text" name="lastName" value="Hambre" />
    <input type="text" name="firstName" value="Jirenz Mae" />
    <input type="text" name="lastNameKana" value="テスト" />
    <input type="text" name="firstNameKana" value="テスト" />
    <input type="text" name="gender" value="" />
    <input type="text" name="birthDay" value="" />
    <input type="text" name="countryCode" value="JP" />
    <input type="text" name="postalCode1" value="157" />
    <input type="text" name="postalCode2" value="0071" />
    <input type="text" name="prefecture" value="sasa" />
    <input type="text" name="address1" value="sasa" />
    <input type="text" name="address2" value="sasa" />
    <input type="text" name="phone1" value="03" />
    <input type="text" name="phone2" value="3333" />
    <input type="text" name="phone3" value="3333" />
    <input type="text" name="subscribeNewsLetter" value="" />
    <button type="submit">Next</button>
</form>