<script type="text/javascript">
    require([
        'jquery',
        'Amasty_Base/vendor/slick/slick.min'
    ], function($,lottie){
        scroll_event();

        $(window).bind("scroll", scroll_event);

        function scroll_event() {
            var now_top = $(this).scrollTop();
            var real_top = now_top + $('#header').height();

            $('.animate').each(function () {
                if (isObjectCenter($(this))) {
                    $(this).addClass('show');
                }
            });

            if (now_top > $('section.sec-mv').offset().top) {
                $('.shopBtn-container').addClass('fixed');
            } else {
                $('.shopBtn-container').removeClass('fixed');
            }
        }

        var userAgent = window.navigator.userAgent.toLowerCase();
        if (userAgent.indexOf('msie') != -1 || userAgent.indexOf('trident') != -1 || userAgent.indexOf('edge') != -1) {
            $('html').addClass('not_full_support');
        }

        // youtube modal window
        $('a.yt_mw').bind('click', function(){
            var id = $(this).attr('data-id');

            var html = '';
            html += '<div class="mw">';
            html += '<div class="mw_bg"></div>';
            html += '<div class="mw_content">';
            html += '<div class="mw_inner">';
            html += '<a href="javascript:void(0);" class="close"><span>CLOSE</span></a>';
            html += '<div class="mw_video">';
            // html += '<iframe frameborder="0" allow="autoplay" allowfullscreen="1" width="640" height="360" src="https://www.youtube.com/embed/'+id+'?rel=0&autoplay=1"></iframe>';
            html += '<iframe frameborder="0" allowfullscreen="1" width="640" height="360" src="https://www.youtube.com/embed/'+id+'?rel=0&autoplay=1"></iframe>';
            html += '</div>';
            html += '</div>';
            html += '</div>';
            html += '</div>';

            $('body').append(html);
            $('.mw').fadeIn(300, function(){
                $('.mw a.close, .mw .mw_bg').bind('click', function(){
                    $('.mw').fadeOut(300, function(){
                        $(this).remove();
                    });
                });
            });
        });
        function isObjectCenter($object) {
            var wh = $(window).height();
            var now_top = $(window).scrollTop();
            var this_top = $object.offset().top;

            if (now_top >= this_top - wh / 2) {
                return true;
            } else {
                return false;
            }
        }
        function isObjectBottom($object, offset) {
            var offset = offset || 0;
            var wh = $(window).height();
            var now_top = $(window).scrollTop();
            var this_top = $object.offset().top;

            if (now_top >= this_top - wh + offset) {
                return true;
            } else {
                return false;
            }
        }
        function isObjectTop($object, offset) {
            var offset = offset || 0;
            var oh = $object.height();
            var now_top = $(window).scrollTop();
            var this_top = $object.offset().top;

            if (now_top >= this_top + oh + offset) {
                return true;
            } else {
                return false;
            }
        }
    });
</script>
