<script type="text/javascript">
    require([
        'jquery'
    ], function($){
        scroll_event();
        $(window).bind("scroll", scroll_event);

        function scroll_event(){
            var now_top = $(this).scrollTop();
            var real_top = now_top + $('#header').height();

            $('.animate').each(function(){
                if(isObjectCenter($(this))){
                    $(this).addClass('show');
                }
            });
        }
        var userAgent = window.navigator.userAgent.toLowerCase();
        if(userAgent.indexOf('msie') != -1 || userAgent.indexOf('trident') != -1 || userAgent.indexOf('edge') != -1){
            $('html').addClass('not_full_support');
        }


        // youtube modal window
        $('a.yt_mw').bind('click', function(){
            var id = $(this).attr('data-id');

            var html = '';
            html += '<div class="mw">';
            html += '<div class="mw_bg"></div>';
            html += '<div class="mw_content">';
            html += '<div class="mw_inner">';
            html += '<a href="javascript:void(0);" class="close"><span>CLOSE</span></a>';
            html += '<div class="mw_video">';
            html += '<iframe frameborder="0" allowfullscreen="1" width="640" height="360" src="https://www.youtube.com/embed/'+id+'?autoplay=1&showinfo=0&rel=0"></iframe>';
            html += '</div>';
            html += '</div>';
            html += '</div>';
            html += '</div>';

            $('body').append(html);
            $('.mw').fadeIn(300, function(){
                $('.mw a.close, .mw .mw_bg').bind('click', function(){
                    $('.mw').fadeOut(300, function(){
                        $(this).remove();
                    });
                });
            });
        });

        function array_shuffle(array) {
            for(var i = array.length - 1; i > 0; i--){
                var r = Math.floor(Math.random() * (i + 1));
                var tmp = array[i];
                array[i] = array[r];
                array[r] = tmp;
            }
            return array;
        }



        function isObjectCenter($object){
            var wh = $(window).height();
            var now_top = $(window).scrollTop();
            var this_top = $object.offset().top;

            if (now_top >= this_top - wh * 0.8){
                return true;
            }else{
                return false;
            }
        }
    });
</script>
