<?php //@codingStandardsIgnoreStart?>
<form id="restock-form" action="<?= $block->getUrl('report/restock/save') ?>" method="post">
    <?= $block->getBlockHtml('formkey'); ?>
    <h2 class="legend"><?= __('Restock Data') ?></h2>
    <div class="field required">
        <label for="from_date" class="label"><span><?= __('From Date') ?></span></label>
        <div class="control">
            <input type="date" name="from_date" id="from_date" required value="" title="<?= __('From Date') ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
    <div class="field required">
        <label for="to_date" class="label"><span><?= __('To Date') ?></span></label>
        <div class="control">
            <input type="date" name="to_date" id="to_date" required value="" title="<?= __('To Date') ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
    <div class="buttons-set">
        <button type="submit" class="action submit primary" title="<?= __('Submit') ?>"><span><?= __('Submit') ?></span></button>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "#myform": {
            "validation": {}
        }
    }
</script>
<?php //@codingStandardsIgnoreEnd?>

<style>
    #restock-form .control input[type=date]{
        border: 1px solid #878787;
        padding: 6px 10px 6px;
    }
    #restock-form label.label{
        display: block;
        font-weight: 600;
        padding-bottom: 10px;
    }
    #restock-form .field{
        margin-bottom: 15px;
    }

</style>
