<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php $_order = $block->getOrder() ?>
<?php $helperOrder = $this->helper(\OnitsukaTiger\Sales\Helper\Data::class)?>
<?php $helperStore = $this->helper(\OnitsukaTiger\Store\Helper\Data::class)?>
<?php $_shipment = $block->getShipment() ?>
<?php if ($_order) : ?>
    <?php $date = $helperStore->formatDate($_order->getCreatedAt(),$_order->getStoreId());?>
<p><strong><?= __('Order Number:')?></strong> <a href="javascript:void(0)"><?= $_order->getIncrementId()?></a></p>
<p><strong><?= __('Order Date:')?></strong> <?= $date?></p>
<p><strong><?= __('Order Total:')?></strong> <?= $_order->formatPrice($_order->getGrandTotal())?></p>
<p><strong><?= __('Shipping & Handling:')?></strong> <?= $_order->formatPrice($_order->getShippingAmount())?></p>
<p><strong><?= __('Promotion Discount:')?></strong> <?= $_order->formatPrice($_order->getDiscountAmount())?></p>
<p><strong><?= __('Order Method:')?></strong> <?= __($_order->getData('shipping_description')) ?></p>
<p><strong><?= __('Order Status:')?></strong> <?= $_order->getStatusLabel() ?></p>
    <?php if($_shipment) : ?>
        <?php foreach ($_shipment->getTracksCollection() as $track): ?>
            <p><strong><?= __('Tracking Number:')?></strong> <a href="javascript:void(0)"><?= $track->getTrackNumber()?></a></p>
        <?php endforeach;?>
    <?php endif; ?>
<?php endif; ?>

