<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Weee\Block\Adminhtml\Items\Price\Renderer $block */

$_item = $block->getItem();
?>

<?php 
    if ($block->getTotalAmount($_item) < 0) {
        echo 0;
    } else {
        echo $block->displayPrices($block->getBaseTotalAmount($_item), $block->getTotalAmount($_item));
    }
?>