<?php
// @codingStandardsIgnoreFile
/** @var $block \WeltPixel\GA4\Block\KlaviyoPixel\Common */

/** @var \WeltPixel\GA4\Helper\KlaviyoPixelTracking $klaviyoPixelHelper */
$klaviyoPixelHelper = $this->helper('WeltPixel\GA4\Helper\KlaviyoPixelTracking');
$cspNonceProvider = $klaviyoPixelHelper->getCspNonceProvider();
?>
<script <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
    let klEventId = <?= /* @noEscape */ $klaviyoPixelHelper->getJsEventIdGenerator() ?>;
</script>
<?php if ($klaviyoPixelHelper->isKlaviyoPixelTrackingEnabled() && $klaviyoPixelHelper->shouldKlaviyoPixelEventBeTracked(\WeltPixel\GA4\Model\Config\Source\KlaviyoPixel\TrackingEvents::EVENT_VIEWED_PAGE)) : ?>
<script <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
    if (window.ga4AllowServices && window.klaviyo) {
        let klaviyoPageData = {
            'PageURL': window.location.href,
            'PageName': document.title,
            'ReferrerURL': document.referrer,
            '$event_id': klEventId
        };

        klaviyo.track('<?= /* @noEscape */ $klaviyoPixelHelper->getKlaviyoEventName(\WeltPixel\GA4\Model\Config\Source\KlaviyoPixel\TrackingEvents::EVENT_VIEWED_PAGE) ?>', klaviyoPageData);
    }
</script>
<?php endif; ?>


<?php if ($klaviyoPixelHelper->isServerSideTrackingEnabled() && $klaviyoPixelHelper->shouldKlaviyoServerSideEventBeTracked(\WeltPixel\GA4\Model\Config\Source\KlaviyoPixel\TrackingEvents::EVENT_VIEWED_PAGE)) : ?>
    <script  <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
        requirejs(['jquery'],
            function  ($) {
                $(document).ready(function() {
                    var requestUrl = '<?php echo $block->escapeUrl($klaviyoPixelHelper->getKlaviyoSSTrackUrl()); ?>';
                    $.post({
                        url: requestUrl,
                        global: false,
                        data: {
                            'eventId': klEventId,
                            'eventName': '<?= /* @noEscape */ \WeltPixel\GA4\Model\Config\Source\KlaviyoPixel\TrackingEvents::EVENT_VIEWED_PAGE  ?>',
                            'PageURL': window.location.href,
                            'PageName': document.title,
                            'ReferrerURL': document.referrer
                        }
                    });
                });
            });
    </script>
<?php endif; ?>
