<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
//phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
//phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
?>
<?php /** @var OnitsukaTigerKorea\Shipping\Block\Adminhtml\Items\Renderer\DefaultRenderer $block */ ?>
<?php $_item = $block->getItem() ?>
<?php $order = $_item->getOrderItem()->getOrder(); ?>
<?php $helperShipping = $this->helper(\OnitsukaTigerKorea\Shipping\Helper\Data::class); ?>
<?php $cancelXmlSynced = $block->getCancelXmlSynced($order); ?>
<tr>
    <td class="col-product"><?= $block->getColumnHtml($_item, 'name') ?></td>
    <td class="col-ordered-qty"><?= $block->getColumnHtml($_item, 'qty') ?></td>
    <td class="col-qty <?php if ($block->isShipmentRegular()) : ?>last<?php endif; ?>">
        <?php if ($block->canShipPartiallyItem()) : ?>
            <input type="text"
                   class="input-text admin__control-text qty-item"
                   name="shipment[items][<?= (int) $_item->getOrderItemId() ?>]"
                   value="<?= /* @noEscape */ $_item->getQty()*1 ?>" />
        <?php else : ?>
            <?= /* @noEscape */ $_item->getQty()*1 ?>
        <?php endif; ?>
    </td>
    <?php if (!$block->canShipPartiallyItem()) : ?>
        <td class="col-ship last">
            <input type="hidden" name="shipment[items][<?= (int) $_item->getOrderItemId() ?>]" value="0" />
            <input type="checkbox"
                   name="shipment[items][<?= (int) $_item->getOrderItemId() ?>]"
                   value="<?= /* @noEscape */ $_item->getQty()*1 ?>" checked />
        </td>
    <?php endif; ?>
    <?php if($helperShipping->isEnabled($_item->getStoreId()) && $order->getOrderSynced() && !$cancelXmlSynced) : ?>
        <td class="col-qty <?php if ($block->isShipmentRegular()) : ?>last<?php endif; ?>">
            <?php if ($block->canShipPartiallyItem()) : ?>
                <input type="text"
                       class="input-text admin__control-text qty-item-cancel"
                       name="shipment[cancel_items][<?= (int) $_item->getOrderItemId($_item->getOrder()) ?>]"
                       value="<?= /* @noEscape */ $_item->getQty()*0 ?>" />
            <?php else : ?>
                <?= /* @noEscape */ $_item->getQty()*0 ?>
            <?php endif; ?>
        </td>
    <?php endif; ?>
</tr>
