<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

$_order   = $block->getOrder();
$creditmemo = $block->getCreditmemo();
$crmHelper = $this->helper(\OnitsukaTigerCpss\Crm\Helper\HelperData::class);

?>

<?php if ($creditmemo && $_order): ?>
    <?php
    $usedPoint = 0;
    $pointValue = 0;
    $pointLabel = 'Points to be earned:';
    if ($_order->getUsedPoint()) {
        $usedPoint = number_format($_order->getUsedPoint());
    }
    if ($_order->getAddedPointDate() > 0 || $_order->getAcquiredPoint() > 0) {
        $pointValue = number_format($_order->getAcquiredPoint());

        if ($_order->getAddedPoint() > 0) {
            $pointLabel = 'Added Points:';
            $pointValue = number_format($_order->getAddedPoint());
        }
    }
    ?>
    <table class="table text-center mb-40">
        <thead>
        <tr>
            <th scope="col">
                <?= $block->escapeHtml(__('No')) ?>
            </th>
            <th scope="col">
                <?= $block->escapeHtml(__('Product No')) ?>
            </th>
            <th scope="col">
                <?= $block->escapeHtml(__('Item Description')) ?>
            </th>
            <th scope="col">
                <?= $block->escapeHtml(__('Quantity')) ?>
            </th>
            <th scope="col">
                <?= $block->escapeHtml(__('Unit Price')) ?>
            </th>
            <th scope="col">
                <?= $block->escapeHtml(__('Subtotal')) ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($creditmemo->getItems() as $_item): ?>
            <?php if (!$_item->getOrderItem()->getParentItem()): ?>
                <tbody>
                <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
    <div class="row">
        <div class="col-8">
        </div>
        <div class="col-2 text-right">
            <?= $block->escapeHtml(__('Shipping:')) ?><br>
            <b><?= $block->escapeHtml(__('Total:')) ?></b><br>
            <?php if ($crmHelper->isEnableModule()): ?>
                <?= /* @noEscape */ __('Used point:') ?><br>
                <?= /* @noEscape */ __($pointLabel) ?>
            <?php endif; ?>
        </div>
        <div class="col-2 text-right">
            <?= /* @noEscape */ $_order->formatPrice($creditmemo->getShippingAmount()) ?><br>
            <?= /* @noEscape */ $_order->formatPrice($creditmemo->getGrandTotal()) ?><br>
            <?php if ($crmHelper->isEnableModule()): ?>
                <?= /* @noEscape */ __($usedPoint) . __(' points')?><br>
                <?= /* @noEscape */ __($pointValue) . __(' points') ?>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
