<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/** @var \Magento\Customer\Block\Form\Edit $block */
use Magento\Framework\App\ObjectManager;
use OnitsukaTigerKorea\Customer\Model\Source\OfflineStoreValue;
use Magento\Customer\Api\CustomerRepositoryInterface;

$linkBlock = $block->getLayout()->createBlock(Seoulwebdesign\KakaoSync\Block\Customer\Link::class);
$linkStatus = $linkBlock->getLinkStatus();

/*$helperConfig = $this->helper(\OnitsukaTigerKorea\Customer\Helper\Data::class);
$niceApiBlock = $block->getLayout()->createBlock(OnitsukaTigerKorea\NiceApiIntegration\Block\Customer\Account\Create::class);
$isModuleEnable = $niceApiBlock->isModuleEnabled();*/

$isKakaoValue = 0;
$customer = $block->getCustomer();

$helperConfig = $this->helper(\OnitsukaTigerKorea\Customer\Helper\Data::class);
$objectManager = ObjectManager::getInstance();
$sourceModel = $objectManager->get(OfflineStoreValue::class);
$options = $sourceModel->toOptionArray();

/** @var \Magento\Customer\Model\Customer $customer */
$selectedValueObj = $customer->getCustomAttribute('offline_store_id');
$selectedValue = $selectedValueObj ? $selectedValueObj->getValue() : null;

$validValues = array_column($options, 'value');
if ($selectedValue && !in_array($selectedValue, $validValues)) {
    $customer->setCustomAttribute('offline_store_id', null);
    $customerRepo = $objectManager->get(CustomerRepositoryInterface::class);
    $customerRepo->save($customer);
    $selectedValue = '';
}

if ($customer && $customer->getCustomAttribute('is_kakao_login')) {
    $isKakaoValue = $customer->getCustomAttribute('is_kakao_login')->getValue();
}
?>
<form class="form form-edit-account" action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <?php if($helperConfig->isKoreanThemeEnable()):?>
            <?= $block->getLayout()->createBlock(\OnitsukaTigerKorea\Customer\Block\Widget\Name::class)->setObject($block->getCustomer())->toHtml() ?>
        <?php else: ?>
            <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getCustomer())->toHtml() ?>
        <?php endif; ?>

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($_dob->isEnabled()) : ?>
            <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php $_shoesSize = $block->getLayout()->createBlock(\OnitsukaTiger\Customer\Block\Widget\ShoesSize::class) ?>
        <?php if ($_shoesSize->isEnabled()) : ?>
            <?= $_shoesSize->setShoesSize(!is_null($block->getCustomer()->getCustomAttribute('shoes_size')) ? $block->getCustomer()->getCustomAttribute('shoes_size')->getValue() : '0')->toHtml() ?>
        <?php endif ?>

        <div class="field offline_store_id">
            <label for="offline_store_id" class="label">
                <span><?= __('선호매장') ?></span>
            </label>
            <div class="control">
                <select name="offline_store_id" id="offline_store_id" <?php if (isset($linkStatus['id'])): ?> style="pointer-events: none; background-color: #f5f5f5; color: #888; border: 1px solid #ccc;" <?php endif;?>>
                    <?php foreach ($options as $option): ?>
                        <option value="<?= $option['value'] ?>" <?= ($selectedValue == $option['value']) ? 'selected="selected"' : '' ?>>
                            <?= $option['label'] ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <!-- add cell phone field start  -->
            <div class="field cell-phone required">
                <label for="cell_phone_input" class="label">
                    <span>
                        <?= $block->escapeHtml(__('휴대폰 번호')) ?>
                    </span>
                </label>
                <div class="control">
                    <input  type="text" <?php if((isset($linkStatus['id']))) { ?> style="pointer-events: none; background-color: #f5f5f5; color: #888; border: 1px solid #ccc;" <?php } ?> name="cell_phone" id="cell_phone_input" class="required-entry" value="<?= !is_null($block->getCustomer()->getCustomAttribute('cell_phone')) ? $block->getCustomer()->getCustomAttribute('cell_phone')->getValue() : ''?>" data-validate="{'validate-number':true}" />
                </div>
            </div>
        <!-- add cell phone field end  -->

        <div class="field choice">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" />
            <label class="label" for="change-email"><span><?= $block->escapeHtml(__('Change Email')) ?></span></label>
        </div>
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()) : ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label" for="change-password"><span><?= $block->escapeHtml(__('Change Password')) ?></span></label>
        </div>
    </fieldset>

    <fieldset class="fieldset password" data-container="change-email-password">
        <legend class="legend"><span data-title="change-email-password"><?= $block->escapeHtml(__('Change Email and Password')) ?></span></legend><br>
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" <?php if((isset($linkStatus['id']))) { ?> style="pointer-events: none; background-color: #f5f5f5; color: #888; border: 1px solid #ccc;" <?php } ?> data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?= $block->escapeHtml(__('Current Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" <?php if (isset($linkStatus['id'])): ?> style="pointer-events: none; background-color: #f5f5f5; color: #888; border: 1px solid #ccc;" <?php endif;?> />            </div>
        </div>
        <div class="field new password required" data-container="new-password">
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-input="new-password"
                       data-validate="{required:true, 'validate-customer-password':true}"
                        <?php if (isset($linkStatus['id'])): ?> style="pointer-events: none; background-color: #f5f5f5; color: #888; border: 1px solid #ccc;" <?php endif;?>
                       autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                       data-input="confirm-password"
                       autocomplete="off" <?php if (isset($linkStatus['id'])): ?> style="pointer-events: none; background-color: #f5f5f5; color: #888; border: 1px solid #ccc;" <?php endif;?> />
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" id="submit-form-edit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"><span><?= $block->escapeHtml(__('Save')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
<script type="text/javascript">
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        dataForm.mage('validation', {
            <?php if ($_dob->isEnabled()) : ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
            <?php else : ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            <?php endif ?>
        }).find('input:text').attr('autocomplete', 'off');
        $(document).on('click', '#submit-form-edit', function(e) {
            if($('#form-validate').valid()) {
                $('#form-validate').trigger('submit');
            }
        });
    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
