<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Register $block */
$crmHelper = $this->helper(\OnitsukaTigerCpss\Crm\Helper\HelperData::class);
$aboutMember = $block->getLayout()->createBlock(OnitsukaTigerCpss\Crm\Block\Member\About::class);
?>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<?php $helperConfig = $this->helper(\OnitsukaTigerKorea\Customer\Helper\Data::class); ?>
<form class="form create account form-create-account" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
    <fieldset class="fieldset create info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Personal Information')) ?></span></legend><br>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <?php if($helperConfig->isKoreanThemeEnable()):?>
            <?= $block->getLayout()->createBlock(\OnitsukaTigerKorea\Customer\Block\Widget\Name::class)->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
        <?php else: ?>
            <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
        <?php endif; ?>
        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php if ($_dob->isEnabled()) : ?>
            <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php
        /** @var \Magento\Framework\View\Element\Template $this */

        use Magento\Framework\App\ObjectManager;
        use Magento\Store\Model\StoreManagerInterface;
        use OnitsukaTigerKorea\Customer\Model\Source\OfflineStoreValue;

        $objectManager = ObjectManager::getInstance();
        $storeManager = $objectManager->get(StoreManagerInterface::class);
        $currentStore = $storeManager->getStore();
        $currentWebsite = $storeManager->getWebsite();

        $storeId = (int) $currentStore->getId();
        $websiteId = (int) $currentWebsite->getId();

        if ($storeId == 5 || $websiteId == 4) {
            $sourceModel = $objectManager->get(OfflineStoreValue::class);
            $options = $sourceModel->toOptionArray();
            $selectedValue = $this->getRequest()->getParam('offline_store_id') ?? '';
            $validValues = array_column($options, 'value');
            if (!in_array($selectedValue, $validValues, true)) {
                $selectedValue = '';
            }
            ?>

            <div class="field offline_store_id">
                <label for="offline_store_id" class="label">
                    <span><?= __('선호 매장') ?></span>
                </label>
                <div class="control">
                    <select name="offline_store_id" id="offline_store_id">
                        <?php foreach ($options as $option): ?>
                            <option value="<?= $option['value'] ?>" <?= ($selectedValue == $option['value']) ? 'selected' : '' ?>>
                                <?= $option['label'] ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

        <?php } ?>
        <?php $_shoesSize = $block->getLayout()->createBlock(\OnitsukaTiger\Customer\Block\Widget\ShoesSize::class) ?>
        <?php if ($_shoesSize->isEnabled()) : ?>
            <?= $_shoesSize->setShoesSize($block->getFormData()->getShoesSize())->toHtml() ?>
        <?php endif ?>
    </fieldset>
    <?php if ($block->getShowAddressFields()) : ?>
        <fieldset class="fieldset address">
            <legend class="legend"><span><?= $block->escapeHtml(__('Address Information')) ?></span></legend><br>
            <input type="hidden" name="create_address" value="1" />

            <?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
            <?php if ($_company->isEnabled()) : ?>
                <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
            <?php endif ?>

            <?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
            <?php if ($_telephone->isEnabled()) : ?>
                <?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
            <?php endif ?>

            <?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
            <?php if ($_fax->isEnabled()) : ?>
                <?= $_fax->setFax($block->getFormData()->getFax())->toHtml() ?>
            <?php endif ?>
            <?php //phpcs:disable ?>
            <?php $_streetValidationClass = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street'); ?>
            <?php //phpcs:enable ?>
            <div class="field street required">
                <label for="street_1" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span></label>
                <div class="control">
                    <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>" id="street_1" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php //phpcs:disable ?>
                        <?php for ($_i = 2, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i <= $_n; $_i++) : ?>
                            <?php //phpcs:enable ?>
                            <div class="field additional">
                                <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                    <span><?= $block->escapeHtml(__('Address')) ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field region hidden">
                <label for="region_id" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span></label>
                <div class="control">
                    <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id" style="display:none;">
                        <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                    </select>
                    <?php //phpcs:disable ?>
                    <input type="text" id="region" name="region" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>" style="display:none;">
                    <?php //phpcs:enable ?>
                </div>
            </div>

            <div class="field country">
                <label for="country" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>

            <div class="field required">
                <label for="city" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
                <div class="control">
                    <?php //phpcs:disable ?>
                    <input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="city">
                    <?php //phpcs:enable ?>
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
                <div class="control">
                    <?php //phpcs:disable ?>
                    <input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
                    <?php //phpcs:enable ?>
                </div>
            </div>

            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes) : ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </fieldset>

    <?php endif; ?>
    <fieldset class="fieldset create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <legend class="legend"><span><?= $block->escapeHtml(__('Sign-in Information')) ?></span></legend><br>
        <div class="field required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" autocomplete="email" id="email_address" value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field password required">
            <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
            <div class="control">
                <input type="password" name="password" id="password"
                       title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                       class="input-text"
                       data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>

        </div>
        <div class="field confirmation required">
            <label for="password-confirmation" class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?></span></label>
            <div class="control">
                <input type="password" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
        <!-- add cell phone text field start -->
        <?php $cellPhone = $block->getLayout()->createBlock(\OnitsukaTiger\Customer\Block\Widget\CellPhone::class) ?>
        <?= $cellPhone->setCellPhone($block->getFormData()->getCellPhone())->toHtml() ?>
        <!-- add cell phone text field end -->

        <?= $block->getChildHtml('form_additional_info') ?>
        <?php if ($block->isNewsletterEnabled()) : ?>
            <!-- <div class="field choice newsletter newsletter-content">
                <input type="checkbox" name="is_subscribed" title="<?= $block->escapeHtmlAttr(__('뉴스레터 수신 동의를 하실 경우, 온라인 쇼핑 ₩20,000의 할인 쿠폰을 보내드립니다.')) ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()) : ?> checked="checked"<?php endif; ?> class="checkbox">
                <label for="is_subscribed" class="label"><?= $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('newsletter-message-information-register')
                ->toHtml();?></label>
            </div> -->
            <?php /* Extensions placeholder */ ?>
            <?= $block->getChildHtml('customer.form.register.newsletter') ?>

            <div class="field choice newsletter message">
                <label class="label">
                    <span><?= $block->escapeHtml(__('약관동의')) ?></span><br>
                    <span><?= $block->escapeHtml(__('신규회원 가입 전, 밑에 명시된 이용 약관을 확인해 주시기 바랍니다.')) ?></span>
                </label>
            </div>
        <?php endif ?>
        <!-- adding select all checkbox start -->
        <div class="field choice agreement newsletter">
            <input type="checkbox" title="" value="1" id="select-all" class="checkbox"">
            <label for="select-all" class="label"><?= __("전체 동의") ?></label>
        </div>
        <!-- adding select all checkbox end -->
        <!-- adding age agreement checkbox start -->
        <div class="field choice agreement newsletter">
            <input type="checkbox" name="agreement[4]" title="" value="1" id="agreement-4" class="checkbox" data-validate="{required:true}">
            <label for="agreement-4" class="label"><?= __("만 14세 이상입니다.") ?></label>
        </div>
        <!-- adding age agreement checkbox end -->

        <div class="field choice agreement newsletter">
            <input type="checkbox" name="agreement[1]" title="" value="1" id="agreement-1" class="checkbox" data-validate="{required:true}">
            <label for="agreement-1" class="label">
                <?= __("이용약관에 동의합니다."); ?> <a target="_blank" href="<?= $block->getUrl()?>terms-and-conditions"> 자세히보기</a>
            </label>
        </div>
        <?php if ($crmHelper->isCpssModuleEnable()):?>
            <!--<div class="about-member-container">-->
            <!--<div class="about-member-service">
                <?php /*= $block->getChildHtml('block_membership_agreement') */?>
            </div>-->
            <div class="field choice agree-member-service agreement newsletter">
                <input type="checkbox" name="is_agreed" title="
            <?= __('멤버십 이용약관에 동의합니다') ?>" id="is_agreed" class="checkbox" data-validate="{required:true}">
                <label for="is_agreed" class="label">
                    <?= __('멤버십 이용약관에 동의합니다.') ?>
                    <a target="_blank" href="<?= $this->getUrl('member-terms-and-conditions')?>" style="text-decoration: underline"><?= __('자세히보기');?></a>
                </label>
            </div>
            <!--</div>-->
        <?php endif ?>
        <div class="field choice agreement newsletter">
            <input type="checkbox" name="agreement[2]" title="" value="1" id="agreement-2" class="checkbox" data-validate="{required:true}">
            <label for="agreement-2" class="label">
                <?= __("개인정보의 필수적 수집·이용에 동의합니다."); ?> <a id="click-open-create-account-popup" href="javascript:void(0)">자세히보기</a>
            </label>
        </div>
        <div id="create-account-popup-modal" style="display:none;">
            <?= $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('create-account-popup-i-agree-to-the-mandatory-content')
                ->toHtml();
            ?>
        </div>

        <div class="field choice agreement newsletter">
            <input type="checkbox" name="custom_newsletter_agreement" title="
            <?= $block->escapeHtmlAttr(__('(선택) 개인정보의 마케팅 활용에 동의합니다.')) ?>" id="custom_newsletter_agreement" class="checkbox">
            <label for="custom_newsletter_agreement" class="label">
                <?= __("(선택) 개인정보의 마케팅 활용에 동의합니다."); ?> <a id="click-open-create-account-popup-optional" href="javascript:void(0)">자세히보기</a>
            </label>
        </div>
        <div id="create-account-popup-modal-optional" style="display:none;">
            <?= $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('create-account-popup-i-agree-to-the-optional-content')
                ->toHtml();
            ?>
        </div>
        <!-- <div class="field choice agreement newsletter">
            <input type="checkbox" name="agreement[3]" title="" value="1" id="agreement-3" class="checkbox" data-validate="{required:true}">
            <label for="agreement-3" class="label">
                개인정보 취급 위탁 동의 <a target="_blank" href="<?= $block->getUrl()?>data-and-privacy-questions">자세히보기</a>                                          </label>
        </div> -->
        <!-- add personal information checkbox start -->
        <?php $personalInformation = $block->getLayout()->createBlock(\OnitsukaTiger\Customer\Block\Widget\PersonalInformation::class) ?>
        <?= $personalInformation->setPersonalInformation($block->getFormData()->getPersonalInformation())->toHtml() ?>
        <!-- add personal information checkbox end -->

        <!-- add advertisement agreement checkbox start -->
        <?php $advertisementAgreement = $block->getLayout()->createBlock(\OnitsukaTiger\Customer\Block\Widget\AdvertisementAgreement::class) ?>
        <?= $advertisementAgreement->setAdvertisementAgreement($block->getFormData()->getAdvertisementAgreement())->toHtml() ?>
        <!-- add advertisement agreement checkbox end -->

    </fieldset>
    <?= $block->getChildHtml('block_customer_content_privacy_policy') ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" id="submit-form-edit" class="action submit primary" title="<?= $block->escapeHtmlAttr(__('회원 가입(만 14세 이상)')) ?>"><span><?= $block->escapeHtml(__('회원 가입(만 14세 이상)')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
        </div>
    </div>
</form>
<script type="text/javascript">
    require([
        'jquery',
        'mage/mage'
    ], function($){

        var dataForm = $('#form-validate');
        var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        dataForm.mage('validation', {
            <?php if ($_dob->isEnabled()) : ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
            <?php else : ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            <?php endif ?>
        }).find('input:text').attr('autocomplete', 'off');
        $(document).on('click', '#submit-form-edit', function(e) {
            if($('#form-validate').valid()) {
                $('#form-validate').trigger('submit');
            }
        });
        $('#select-all').click(function() {
            var checked = $(this).prop('checked');
            $('input:checkbox').prop('checked', checked);
        });
    });
</script>
<?php if ($block->getShowAddressFields()) : ?>
    <script type="text/x-magento-init">
        {
            "#country": {
                "regionUpdater": {
                    "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
        <?php //phpcs:disable ?>
        "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
        <?php //phpcs:enable ?>
        "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
        <?php //phpcs:disable ?>
        "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
                <?php //phpcs:enable ?>
        }
    }
}
    </script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($,modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                modalClass: 'create-account-popup-custome',
                title: '',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }],
                opened: function($Event) {
                    $(".modal-footer").hide();
                }
            };

            var popup = modal(options, $('#create-account-popup-modal'));
            var popupOptional = modal(options, $('#create-account-popup-modal-optional'));
            $("#click-open-create-account-popup").on('click',function(){
                $("#create-account-popup-modal").modal("openModal");
            });
            $("#click-open-create-account-popup-optional").on('click',function(){
                $("#create-account-popup-modal-optional").modal("openModal");
            });

        }
    );
</script>
