<?php $helper = $this->helper(\OnitsukaTiger\Checkout\Helper\Data::class); ?>
<?php $helperOrder = $this->helper(\OnitsukaTiger\Sales\Helper\Data::class)?>
<?php $helperFixture = $this->helper(\OnitsukaTiger\Fixture\Helper\Data::class);?>
<?php $helperStore = $this->helper(\OnitsukaTiger\Store\Helper\Data::class);?>
<?php $_order = $helper->getOrderByIncrementId($block->getOrder()) ?>
<?php $date = $helperStore->formatDate($_order->getCreatedAt(),$_order->getStoreId());?>
<?php $items = $block->getReturnItems();?>
<?php $helperData = $this->helper(OnitsukaTigerKorea\ConfigurableProduct\Helper\Data::class);?>
<?php $crmHelper = $this->helper(\OnitsukaTigerCpss\Crm\Helper\HelperData::class)?>
<?php $prices = 0;?>
<?php if ($_order) : ?>
    <?php $_items = $_order->getAllItems(); ?>
    <?php if ($items):
        foreach ($items as $item): ?>
            <?php foreach ($_items as $_item) : ?>
                <?php if (!$_item->getParentItem()) : ?>
                    <?php if($_item->getSku() != $item->getItemSku()): continue;?><?php endif;?>
                    <?php $prices += (float)$_item->getPrice();?>
                <?php endif; ?>
            <?php endforeach;?>
        <?php endforeach;
    endif;?>
    <?php
    $usedPoint = 0;
    $pointValue = 0;
    $pointLabel = 'Points to be earned:';
    if ($_order->getUsedPoint()) {
        $usedPoint = number_format($_order->getUsedPoint());
    }
    if ($_order->getAddedPointDate() > 0 || $_order->getAcquiredPoint() > 0) {
        $pointValue = number_format($_order->getAcquiredPoint());

        if ($_order->getAddedPoint() > 0) {
            $pointLabel = 'Added Points:';
            $pointValue = number_format($_order->getAddedPoint());
        }
    }
    ?>
    <table style="width:100%" cellspacing="0" cellpadding="0">
        <tr class="email-summary">
            <td class="order-information">
                <p><strong><?= __('Order Number:')?></strong> <?= $_order->getIncrementId()?></p>
                <p><strong><?= __('Order Date:')?></strong> <?= $date?></p>
                <p><strong><?= __('Order Total:')?></strong> <?= $_order->formatPrice($_order->getGrandTotal())?></p>
                <?php if ($crmHelper->isEnableModule()): ?>
                    <p><strong><?= /* @noEscape */ __('Used point:') ?></strong>
                        <?= /* @noEscape */ $block->escapeHtml($usedPoint) . __(' points') ?></p>
                    <p><strong><?= /* @noEscape */ __($pointLabel) ?></strong>
                        <?= /* @noEscape */ $block->escapeHtml($pointValue) . __(' points') ?></p>
                <?php endif; ?>
                <p><strong><?= __('Shipping & Handling:')?></strong> <?= $_order->formatPrice($_order->getShippingAmount())?></p>
                <p><strong><?= __('Promotion Discount:')?></strong> <?= $_order->formatPrice($_order->getDiscountAmount())?></p>
                <p><strong><?= __('Order Method:')?></strong> <?= __('Home Delivery')?></p>
                <p><strong><?= __('Order Status:')?></strong> <?= __('Delivered'); ?></p>
            </td>
        </tr>
    </table>
    <p class="space-order-items">&nbsp;</p>
    <div class="order-items-content">
        <table class="email-items" border="0" cellspacing="0" cellpadding="0">
            <thead>
            <tr>
                <th class="item-info">
                    <div>
                        <?= $block->escapeHtml(__('Item(s)')) ?>
                    </div>
                </th>
                <th class="item-name">
                    <div>
                        <?= $block->escapeHtml(__('Name')) ?>
                    </div>
                </th>
                <th class="item-qty">
                    <div>
                        <?= $block->escapeHtml(__('Quantity')) ?>
                    </div>
                </th>
                <th class="item-price" style=" border-right: 1px solid #000000;">
                    <div>
                        <?= $block->escapeHtml(__('Price')) ?>
                    </div>
                </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_items as $_item) : ?>
                <?php if (!$_item->getParentItem()) : ?>
                    <?php
                    $productOption = $_item->getProductOptions();
                    $catalogHelper = $this->helper(\Magento\Catalog\Helper\Image::class);
                    $options = $helper->getItemOptions($_item);

                    $helperReturn = $this->helper(\OnitsukaTiger\Rma\Helper\Data::class);
                    $productForThumbnail = $helperReturn->getFinalProductThumbnail($_item, $_order);

                    /** @var \Vaimo\OTScene7Integration\Helper\Data $scene7Helper */
                    $scene7Helper = $this->helper(\Vaimo\OTScene7Integration\Helper\Data::class);
                    $image_url = $scene7Helper->getOrderItemProductImage($productForThumbnail, "order_item_image_size");
                    $productHelper = $this->helper(\OnitsukaTiger\Catalog\Helper\Data::class);
                    $product = $productHelper->getProduct($_item->getSku());
                    $color = $product->getResource()->getAttribute('color');
                    $colorValue = $color->getSource()->getOptionText($product->getData('color'));
                    ?>
                    <tr>
                        <td class="item-info">
                            <img src="<?= $image_url ?>" alt="<?= $block->escapeHtml($_item->getName()) ?>"/>
                        </td>
                        <td class="item-name">
                            <div class="product-information">
                                <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
                                <p class="sku"><?= $block->escapeHtml(__('Style')) ?> #: <?= $block->escapeHtml($_item->getSku()) ?></p>
                                <?php if ($options) : ?>
                                    <div class="product-options">
                                        <ul>
                                            <?php foreach ($options as $_option) : ?>
                                                <li>
                                                    <?php $sizeForDisplay = $helperData->getSizeForDisplay($_item->getSku(), $_item->getStoreId())?>
                                                    <?php if ($sizeForDisplay && strtolower(__($_option['label'])) == 'size') : ?>
                                                        <?= $block->escapeHtml($_option['label']) ?> : <?= /* @noEscape */ nl2br($block->escapeHtml($sizeForDisplay)) ?>
                                                    <?php elseif ($colorValue && strtolower(__($_option['label'])) == 'colors') : ?>
                                                        <?= $block->escapeHtml($_option['label']) ?> : <?= /* @noEscape */ nl2br($block->escapeHtml($colorValue)) ?>
                                                    <?php else :?>
                                                        <?= $block->escapeHtml($_option['label']) ?> : <?= /* @noEscape */ nl2br($block->escapeHtml($_option['print_value'] ?? $_option['value'])) ?>
                                                    <?php endif; ?>
                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </td>
                        <td class="item-qty"><?= (float) $_item->getQtyOrdered() ?></td>
                        <td class="item-price" style=" border-right: 1px solid #000000;">
                            <?php if((int)$helperFixture->getConfig('tax/cart_display/subtotal') == 1):?>
                                <?= /* @noEscape */ $_order->formatPrice($_item->getPrice()) ?>
                            <?php else: ?>
                                <?= /* @noEscape */ $_order->formatPrice($_item->getPriceInclTax()) ?>
                            <?php endif;?>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <p class="space-order-items">&nbsp;</p>
<?php endif; ?>
