<?php

namespace OnitsukaTiger\QuickPurchaseWelt\Preference\GA4\Helper;

class Data extends \WeltPixel\GA4\Helper\Data
{
    /**
     * AddDefaultInformation Function
     *
     * @return void
     */
    public function addDefaultInformation()
    {
        parent::addDefaultInformation(); // TODO: Change the autogenerated stub
        $visitorId = $this->getVisitorId();
        if (!empty($visitorId)) {
            $this->storage->setData('visitor_id', $visitorId);
        }
    }

    /**
     * AddCategoryPageInformation Function
     *
     * @return void
     */
    public function addCategoryPageInformation()
    {
        parent::addCategoryPageInformation(); // TODO: Change the autogenerated stub
        $visitorId = $this->getVisitorId();
        if (!empty($visitorId)) {
            $this->storage->setData('visitor_id', $visitorId);
        }
    }

    /**
     * AddSearchResultPageInformation Function
     *
     * @return void
     */
    public function addSearchResultPageInformation()
    {
        parent::addSearchResultPageInformation(); // TODO: Change the autogenerated stub
        $visitorId = $this->getVisitorId();
        if (!empty($visitorId)) {
            $this->storage->setData('visitor_id', $visitorId);
        }
    }

    /**
     * AddProductPageInformation Function
     *
     * @return void
     */
    public function addProductPageInformation()
    {
        parent::addProductPageInformation(); // TODO: Change the autogenerated stub
        $visitorId = $this->getVisitorId();
        if (!empty($visitorId)) {
            $this->storage->setData('visitor_id', $visitorId);
        }
    }

    /**
     * AddCartPageInformation Function
     *
     * @return void
     */
    public function addCartPageInformation()
    {
        parent::addCartPageInformation(); // TODO: Change the autogenerated stub
        $visitorId = $this->getVisitorId();
        if (!empty($visitorId)) {
            $this->storage->setData('visitor_id', $visitorId);
        }
    }

    /**
     * AddCheckoutInformation Function
     *
     * @return void
     */
    public function addCheckoutInformation()
    {
        parent::addCheckoutInformation(); // TODO: Change the autogenerated stub
        $visitorId = $this->getVisitorId();
        if (!empty($visitorId)) {
            $this->storage->setData('visitor_id', $visitorId);
        }
    }

    /**
     * AddOrderInformation Function
     *
     * @return void
     */
    public function addOrderInformation()
    {
        parent::addOrderInformation(); // TODO: Change the autogenerated stub
        $visitorId = $this->getVisitorId();
        if (!empty($visitorId)) {
            $this->storage->setData('visitor_id', $visitorId);
        }
    }

    /**
     * Get Visitor Id
     *
     * @return string|null
     */
    public function getVisitorId()
    {
        $visitorId = $this->cookieManager->getCookie('visitor_id') ?? '';
        if (!empty($visitorId)) {
            return $visitorId;
        }
        return $visitorId;
    }
}