<?php
// @codingStandardsIgnoreFile
/** @var $block \WeltPixel\GA4\Block\RedditPixel\Common */

/** @var \WeltPixel\GA4\Helper\RedditPixelTracking $redditPixelHelper */
$redditPixelHelper = $this->helper('WeltPixel\GA4\Helper\RedditPixelTracking');
$cspNonceProvider = $redditPixelHelper->getCspNonceProvider();
$orderId = $block->getOrderId();
?>
<script <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
    let redditPurchaseEventId = <?= /* @noEscape */ $redditPixelHelper->getJsEventIdGenerator() ?>;
</script>
<?php if ($redditPixelHelper->isRedditPixelTrackingEnabled() &&
    $block->shouldRedditPixelEventBeTracked(\WeltPixel\GA4\Model\Config\Source\RedditPixel\TrackingEvents::EVENT_PURCHASE) &&
    $redditPixelHelper->isOrderTrackingAllowedBasedOnOrderStatus($block->getOrder())) :
    ?>
    <script  <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
        if (window.ga4AllowServices) {
            rdt('track', 'Purchase', {
                products: <?= /* @noEscape */ $block->getProductsForPurchase() ?>,
                currency: "<?= /* @noEscape */ $redditPixelHelper->getCurrencyCode() ?>",
                itemCount: <?= /* @noEscape */ $block->getOrderItemCount() ?>,
                transactionId: "<?= /* @noEscape */ $block->getOrderTransactionId() ?>",
                value: "<?= /* @noEscape */ $block->getOrderValue() ?>",
                conversionId: redditPurchaseEventId
            });
        }
    </script>
<?php endif; ?>


<?php if ($redditPixelHelper->isServerSideTrackingEnabled() &&
    $redditPixelHelper->shouldRedditServerSideEventBeTracked(\WeltPixel\GA4\Model\Config\Source\RedditPixel\TrackingEvents::EVENT_PURCHASE) &&
    $redditPixelHelper->isOrderTrackingAllowedBasedOnOrderStatus($block->getOrder())) : ?>
    <script  <?php if ($cspNonceProvider) /* @noEscape */ echo ' nonce="' .  $cspNonceProvider->generateNonce() . '" ' ?>>
        requirejs(['jquery'],
            function  ($) {
                $(document).ready(function() {
                    var requestUrl = '<?php echo $block->escapeUrl($redditPixelHelper->getRedditSSTrackUrl()); ?>';
                    $.post({
                        url: requestUrl,
                        global: false,
                        data: {
                            'eventId': redditPurchaseEventId,
                            'eventName': '<?= /* @noEscape */ \WeltPixel\GA4\Model\Config\Source\RedditPixel\TrackingEvents::EVENT_PURCHASE  ?>',
                            'pageUrl': '<?= $block->escapeUrl($redditPixelHelper->getStoreCurrenUrl()) ?>',
                            'orderId': '<?=  /* @noEscape */ $orderId ?>'
                        }
                    });
                });
            });
    </script>
<?php endif; ?>
