@font-face {
    font-family: 'THSarabunNew';
    src: url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew-webfont.eot"); ?>);
    src: url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew-webfont.eot?#iefix"); ?>) format('embedded-opentype'),
    url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew-webfont.woff"); ?>) format('woff'),
    url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew-webfont.ttf"); ?>) format('truetype');
    font-weight: normal;
    font-style: normal;
    font-display: block;
}

@font-face {
    font-family: 'THSarabunNew';
    src: url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_bolditalic-webfont.eot"); ?>);
    src: url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_bolditalic-webfont.eot?#iefix"); ?>) format('embedded-opentype'),
    url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_bolditalic-webfont.woff"); ?>) format('woff'),
    url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_bolditalic-webfont.ttf"); ?>) format('truetype');
    font-weight: bold;
    font-style: italic;
    font-display: block;
}

@font-face {
    font-family: 'THSarabunNew';
    src: url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_italic-webfont.eot"); ?>);
    src: url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_italic-webfont.eot?#iefix"); ?>) format('embedded-opentype'),
    url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_italic-webfont.woff"); ?>) format('woff'),
    url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_italic-webfont.ttf"); ?>) format('truetype');
    font-weight: normal;
    font-style: italic;
    font-display: block;
}

@font-face {
    font-family: 'THSarabunNew';
    src: url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_bold-webfont.eot"); ?>);
    src: url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_bold-webfont.eot?#iefix"); ?>) format('embedded-opentype'),
    url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_bold-webfont.woff"); ?>) format('woff'),
    url(<?php echo $block->getViewFileUrl("OnitsukaTiger_EmailToWareHouse::fonts/thsarabunnew_bold-webfont.ttf"); ?>) format('truetype');
    font-weight: bold;
    font-style: normal;
    font-display: block;
}
