<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/** @var \OnitsukaTigerKorea\Customer\Block\Widget\Name $block */

$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();
/*$niceApiBlock = $block->getLayout()->createBlock(OnitsukaTigerKorea\NiceApiIntegration\Block\Customer\Account\Create::class);
$niceApiResponse = $niceApiBlock->getNiceApiResponse();
$isModuleEnable = $niceApiBlock->IsModuleEnabled();*/
/** @var \Magento\Framework\App\RequestInterface $request */
$request = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\App\RequestInterface::class);
$isEditAccountPage = ($request->getFullActionName() === 'customer_account_edit');
$linkBlock = $block->getLayout()->createBlock(Seoulwebdesign\KakaoSync\Block\Customer\Link::class);
$linkStatus = $linkBlock->getLinkStatus();
$isKakaoLogin = 0;
if ($block->getObject() && $block->getObject()->getCustomAttribute('is_kakao_login')) {
    $isKakaoLogin = (int)$block->getObject()->getCustomAttribute('is_kakao_login')->getValue();
}
?>
<?php if (($prefix || $middle || $suffix) && !$block->getNoWrap()) : ?>
<div class="field required fullname <?= $block->escapeHtmlAttr($block->getContainerClassName()) ?>">
    <label for="<?= $block->escapeHtmlAttr($block->getFieldId('firstname')) ?>"
           class="label"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
    <div class="control">
        <fieldset class="fieldset fieldset-fullname">
            <div class="fields">
                <?php endif; ?>

                <?php if ($prefix) : ?>
                    <div class="field field-name-prefix<?= $block->isPrefixRequired() ? ' required' : '' ?>">
                        <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('prefix')) ?>"><span><?= $block->escapeHtml($block->getStoreLabel('prefix')) ?></span></label>
                        <div class="control">
                            <?php if ($block->getPrefixOptions() === false) : ?>
                                <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('prefix')) ?>"
                                       name="<?= $block->escapeHtmlAttr($block->getFieldName('prefix')) ?>"
                                       value="<?= $block->escapeHtmlAttr($block->getObject()->getPrefix()) ?>"
                                       title="<?= $block->escapeHtmlAttr($block->getStoreLabel('prefix')) ?>"
                                       class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('prefix')) ?>" <?= $block->isPrefixRequired() ? ' data-validate="{required:true}"' : '' ?>>
                            <?php else : ?>
                                <select id="<?= $block->escapeHtmlAttr($block->getFieldId('prefix')) ?>"
                                        name="<?= $block->escapeHtmlAttr($block->getFieldName('prefix')) ?>"
                                        title="<?= $block->escapeHtmlAttr($block->getStoreLabel('prefix')) ?>"
                                        class="<?= $block->escapeHtmlAttr($block->getAttributeValidationClass('prefix')) ?>" <?= $block->isPrefixRequired() ? ' data-validate="{required:true}"' : '' ?> >
                                    <?php foreach ($block->getPrefixOptions() as $_option) : ?>
                                        <option value="<?= $block->escapeHtmlAttr($_option) ?>"<?php if ($block->getObject()->getPrefix() == $_option) : ?> selected="selected"<?php endif; ?>>
                                            <?= $block->escapeHtml(__($_option)) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="field field-name-firstname required">
                    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('firstname')) ?>"><span><?= $block->escapeHtml($block->getStoreLabel('firstname')) ?></span></label>
                    <div class="control">
                        <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('firstname')) ?>"
                               name="<?= $block->escapeHtmlAttr($block->getFieldName('firstname')) ?>"
                                <?php if($block->getObject()->getFirstname() && $isEditAccountPage && (isset($linkStatus['id']))) { ?>
                                    value="<?= $block->getObject()->getFirstname() ?>" readonly
                                    style="pointer-events: none;background-color: #f5f5f5;color: #888;border: 1px solid #ccc;"
                                <?php } else { ?>
                                    value="<?= $block->escapeHtmlAttr($block->getObject()->getFirstname()) ?>"
                                <?php } ?>
                               title="<?= $block->escapeHtmlAttr($block->getStoreLabel('firstname')) ?>"
                               class="validate-length maximum-length-32 input-text xml-hangul-validate <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('firstname')) ?>" <?= ($block->getAttributeValidationClass('firstname') == 'required-entry') ? ' data-validate="{required:true}"' : '' ?>>
                    </div>
                </div>
                <?php if ($middle) : ?>
                    <?php $isMiddlenameRequired = $block->isMiddlenameRequired(); ?>
                    <div class="field field-name-middlename<?= $isMiddlenameRequired ? ' required' : '' ?>">
                        <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('middlename')) ?>"><span><?= $block->escapeHtml($block->getStoreLabel('middlename')) ?></span></label>
                        <div class="control">
                            <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('middlename')) ?>"
                                   name="<?= $block->escapeHtmlAttr($block->getFieldName('middlename')) ?>"
                                   value="<?= $block->escapeHtmlAttr($block->getObject()->getMiddlename()) ?>"
                                   title="<?= $block->escapeHtmlAttr($block->getStoreLabel('middlename')) ?>"
                                   class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('middlename')) ?>" <?= $isMiddlenameRequired ? ' data-validate="{required:true}"' : '' ?>>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="field field-name-lastname hidden">
                    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('lastname')) ?>"><span><?= $block->escapeHtml($block->getStoreLabel('lastname')) ?></span></label>
                    <div class="control">
                        <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('lastname')) ?>"
                               name="<?= $block->escapeHtmlAttr($block->getFieldName('lastname')) ?>"
                               value="<?= $block->escapeHtmlAttr($block->getObject()->getLastname()) ?>"
                               title="<?= $block->escapeHtmlAttr($block->getStoreLabel('lastname')) ?>"
                               class="validate-length maximum-length-255 input-text">
                    </div>
                </div>
                <?php if ($suffix) : ?>
                    <div class="field field-name-suffix<?= $block->isSuffixRequired() ? ' required' : '' ?>">
                        <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('suffix')) ?>"><span><?= $block->escapeHtml($block->getStoreLabel('suffix')) ?></span></label>
                        <div class="control">
                            <?php if ($block->getSuffixOptions() === false) : ?>
                                <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('suffix')) ?>"
                                       name="<?= $block->escapeHtmlAttr($block->getFieldName('suffix')) ?>"
                                       value="<?= $block->escapeHtmlAttr($block->getObject()->getSuffix()) ?>"
                                       title="<?= $block->escapeHtmlAttr($block->getStoreLabel('suffix')) ?>"
                                       class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('suffix')) ?>" <?= $block->isSuffixRequired() ? ' data-validate="{required:true}"' : '' ?>>
                            <?php else : ?>
                                <select id="<?= $block->escapeHtmlAttr($block->getFieldId('suffix')) ?>"
                                        name="<?= $block->escapeHtmlAttr($block->getFieldName('suffix')) ?>"
                                        title="<?= $block->escapeHtmlAttr($block->getStoreLabel('suffix')) ?>"
                                        class="<?= $block->escapeHtmlAttr($block->getAttributeValidationClass('suffix')) ?>" <?= $block->isSuffixRequired() ? ' data-validate="{required:true}"' : '' ?>>
                                    <?php foreach ($block->getSuffixOptions() as $_option) : ?>
                                        <option value="<?= $block->escapeHtmlAttr($_option) ?>"<?php if ($block->getObject()->getSuffix() == $_option) : ?> selected="selected"<?php endif; ?>>
                                            <?= $block->escapeHtml(__($_option)) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endif; ?>

                <?php if (($prefix || $middle || $suffix) && !$block->getNoWrap()) : ?>
            </div>
        </fieldset>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "hangulCharactersValidate": {}
        }
    }
</script>
<script type="text/javascript">
    localStorage.removeItem('url_with_parameters');
</script>
