<?php
$helper = $this->helper(\OnitsukaTiger\Customer\Helper\Data::class);
?>
<?php $_order = $block->getOrder() ?>
<?php
$helperConfig = $this->helper(\OnitsukaTiger\Fixture\Helper\Data::class);
$telephonePrefix = $helperConfig->getConfig('general/telephone_prefix/number') ? $helperConfig->getConfig('general/telephone_prefix/number') : '66';
?>
<?php if ($_order) : ?>
    <p class="title-address"><?= __('Shipping Address')?></p>
    <?php if($_order->getShippingAddress()):?>
        <?= $_order->getShippingAddress()->getFirstName()?> <?= $_order->getShippingAddress()->getLastName()?> <br/>
        <?php foreach ($_order->getShippingAddress()->getStreet() as $street): ?>
            <?= $block->escapeHtml($street) ?>,
        <?php endforeach;?><br/>
        <?= $_order->getShippingAddress()->getCity() ?>, <?= $_order->getShippingAddress()->getRegion() ?><br/>
        <?= $helper->getCountryByCode($_order->getShippingAddress()->getCountryId())?><br/>
        <?= __('Postal Code:')?> <?= $_order->getShippingAddress()->getPostcode()?>,<br/>
        <?php if($helperConfig->getConfig('general/telephone_prefix/enable')): ?>
            <?= __('Mobile:')?> <?= $telephonePrefix.'-'.substr($block->escapeHtml($_order->getShippingAddress()->getTelephone()), 2) ?><br/>
        <?php else: ?>
            <?= __('Mobile:')?> <?= $block->escapeHtml($_order->getShippingAddress()->getTelephone()) ?><br/>
        <?php endif;?>
        <?= __('Email:')?> <a href="mailto:<?= $_order->getShippingAddress()->getEmail()?>"><?= $_order->getShippingAddress()->getEmail()?></a>
    <?php endif; ?>
<?php endif; ?>
