<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Creditmemo\Items */
?>
<?php $_order = $block->getOrder() ?>
<?php $helperOrder = $this->helper(\OnitsukaTiger\Sales\Helper\Data::class) ?>
<?php $helperStore = $this->helper(\OnitsukaTiger\Store\Helper\Data::class) ?>
<?php $crmHelper = $this->helper(\OnitsukaTigerCpss\Crm\Helper\HelperData::class) ?>
<?php $_creditMemo = $block->getCreditmemo() ?>
<?php if ($_order) : ?>
<?php $date = $helperStore->formatDate($_order->getCreatedAt(), $_order->getStoreId()); ?>
<?php
    $usedPoint = 0;
    $pointValue = 0;
    $pointDiscount = 0;
    $pointLabel = 'Points to be earned:';
    if ($_order->getUsedPoint()) {
        $usedPoint = number_format($_order->getUsedPoint());
        $pointDiscount = $_order->getUsedPoint() / 100;
    }
    if ($_order->getAddedPointDate() > 0 || $_order->getAcquiredPoint() > 0) {
        $pointValue = number_format($_order->getAcquiredPoint());

        if ($_order->getAddedPoint() > 0) {
            $pointLabel = 'Added Points:';
            $pointValue = number_format($_order->getAddedPoint());
        }
    }
    $promotionDiscount = $_order->getDiscountAmount();
    if ($pointDiscount > 0) {
        $promotionDiscount = $promotionDiscount - $pointDiscount;
    }
?>

<?php
    $cItems = $_creditMemo->getAllItems();
    $refundedPoint = 0;
    foreach ($cItems as $item) {
        $oItem = $item->getOrderItem();
        if (!$oItem->getParentItemId()) {
            continue;
        }
        $orderQty = (int)$oItem->getQtyOrdered();
        $returnQty = (int)$item->getQty();
        $returnPoints = ($oItem->getUsedPoint() / $orderQty) * $returnQty;
        $refundedPoint += $returnPoints;
    }

    if ($refundedPoint > 0) {
        $refundedPoint = number_format($refundedPoint * 100);
    }
?>
    <p><strong><?= __('Order Number:') ?></strong> <a href="javascript:void(0)"><?= $_order->getIncrementId() ?></a></p>
    <p><strong><?= __('Order Date:') ?></strong> <?= $date ?></p>
    <p><strong><?= __('Order Total:') ?></strong> <?= $block->getOrder()->formatPrice($_order->getGrandTotal()) ?></p>
    <?php if ($crmHelper->isCpssModuleEnable()): ?>
        <p><strong><?= /* @noEscape */
                __('Used point:') ?></strong>
            <?= /* @noEscape */
            $block->escapeHtml($usedPoint) . __(' points') ?></p>
        <?php if ($refundedPoint > 0) :?>
            <p><strong><?= /* @noEscape */
                    __('Refunded point:') ?></strong>
                <?= /* @noEscape */
                $block->escapeHtml($refundedPoint) . __(' points') ?></p>
        <?php endif;?>
        <p><strong><?= /* @noEscape */
                __($pointLabel) ?></strong>
            <?= /* @noEscape */
            $block->escapeHtml($pointValue) . __(' points') ?></p>
    <?php endif; ?>
    <p>
        <strong><?= __('Shipping & Handling:') ?></strong> <?= $block->getOrder()->formatPrice($_order->getShippingAmount()) ?>
    </p>
    <?php if ($pointDiscount > 0): ?>
        <p><strong><?= __('Point Discount:') ?></strong> <?= $block->getOrder()->formatPrice($pointDiscount) ?></p>
    <?php endif; ?>
    <p>
        <strong><?= __('Promotion Discount:') ?></strong> <?= $block->getOrder()->formatPrice($promotionDiscount) ?>
    </p>
    <p><strong><?= __('Order Method:') ?></strong> <?= __('Home Delivery') ?></p>
    <p><strong><?= __('Order Status:') ?></strong> <?= __('Refund Processed'); ?></p>
<?php endif; ?>
<?php if ($_creditMemo): ?>
    <p>
        <strong><?= __('Refund Amount:') ?></strong> <?= $block->getOrder()->formatPrice($_creditMemo->getGrandTotal()) ?>
    </p>
<?php endif; ?>
