<?php /* @var $this  \Magento\Framework\View\TemplateEngine\Php  */ ?>
<?php /* @var $block \Seoulwebdesign\Kpostcode\Block\PostCode */ ?>
<script>
    window.kPostCodeConfig = {
    	isEnable: '<?php echo $this->helper("Seoulwebdesign\Kpostcode\Helper\Data")->isEnable() ?>',
        language : '<?php echo $block->getLanguages(); ?>',
        postCodeIcoStr : '<?php echo $block->getViewFileUrl('Seoulwebdesign_Kpostcode::images/postcode-ico.png'); ?>',
        popupTitle: '<?php echo $this->helper("Seoulwebdesign\Kpostcode\Helper\Data")->getPopupTitle() ?>',
        version: '<?php echo $this->helper("Seoulwebdesign\Kpostcode\Helper\Data")->getSelectedVersion() ?>',
        mode: '<?php echo $this->helper("Seoulwebdesign\Kpostcode\Helper\Data")->getSelectedMode() ?>',
        showJibun: '<?php echo $this->helper("Seoulwebdesign\Kpostcode\Helper\Data")->getShowJibun() ?>',

    }
</script>
