<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>


<?php if ($_product->isSaleable()) :?>
<div class="pre-order-delivery-date">
    <span></span>
</div>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>

            <span class="coming-soon-text-pdp" style="color:#FF0000;display: none;"><?= $block->escapeHtml(__("This item is not yet on sale.")) ?></span>

        </div>
        <div class="stock-alert-custom">
            <button id="button-alert-custom" class="alert default" style="display: none;">
                <span><?= $block->escapeHtml(__("Restock Mail")) ?></span>
            </button>
            <button id="button-alert-pre-custom" class="alert pre-order" style="display: none;">
                <span><?= $block->escapeHtml(__("Pre-order Mail")) ?></span>
            </button>
            <button id="button-reserved-custom" class="action primary tocart reserved" style="display: none;">
                <span><?= $block->escapeHtml(__("Reserved")) ?></span>
            </button>
            <button id="button-soldout-custom" class="soldout" disabled="disabled" style="display: none;">
                <span><?= $block->escapeHtml(__("Sold Out")) ?></span>
            </button>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Catalog/js/restock": {
            "pageIdentifier": "product_view_page"
        }
    }
}
</script>
