<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div class="search-button">
    <span>&nbsp;</span>
</div>
<div class="block block-search">
    <div class="block block-title"><strong><?= $escaper->escapeHtml(__('Search')) ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?= $block->escapeHtml(__('Search')) ?></span>
                </label>
                <div class="control">
                    <input id="search"
                           type="text"
                           name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                           value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                           placeholder="<?= $escaper->escapeHtmlAttr(__('SEARCH...')) ?>"
                           class="input-text"
                           maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"
                           aria-expanded="false"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtml(__('Search')) ?>"
                        class="action search"
                        aria-label="Search"
                >
                    <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
