<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \OnitsukaTiger\Checkout\Block\Onepage\Success\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php
$helper = $this->helper(\OnitsukaTiger\Customer\Helper\Data::class);
$helperConfig = $this->helper(\OnitsukaTiger\Fixture\Helper\Data::class);
$helperConfigTheme = $this->helper(\OnitsukaTigerKorea\Customer\Helper\Data::class);
$telephonePrefix = $helperConfig->getConfig('general/telephone_prefix/number') ? $helperConfig->getConfig('general/telephone_prefix/number') : '66';
?>
<?php if($helperConfigTheme->isKoreanThemeEnable()):?>
    <div class="block block-order-details-view">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Order Information')) ?></strong>
        </div>
        <div class="block-content">
            <?php if (!$_order->getIsVirtual()) : ?>
                <div class="box box-order-shipping-address">
                    <strong class="box-title"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></strong>
                    <div class="box-content">
                        <?= $block->escapeHtml($_order->getShippingAddress()->getFirstname()) ?>,<br/>
                        <?php foreach ($_order->getShippingAddress()->getStreet() as $street): ?>
                            <?= $street ?>,<br/>
                        <?php endforeach;?>
                        <?php if($_order->getShippingAddress()->getCity() != ''): ?>
                            <?= $block->escapeHtml($_order->getShippingAddress()->getCity()) ?> -
                        <?php endif; ?>
                        <?= $block->escapeHtml($_order->getShippingAddress()->getPostcode()) ?>, <?= $helper->getCountryByCode($_order->getShippingAddress()->getCountryId())?><br/>
                        <?= $_order->getCustomerEmail()?><br/>
                        <?php if($helperConfig->getConfig('general/telephone_prefix/enable')): ?>
                            <?= $telephonePrefix.'-'.substr($block->escapeHtml($_order->getShippingAddress()->getTelephone()), 2) ?>
                        <?php else: ?>
                            <?= $_order->getShippingAddress()->getTelephone() ?>
                        <?php endif;?>

                    </div>
                </div>
            <?php endif; ?>

            <div class="box box-order-billing-address">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Billing Address')) ?></span>
                </strong>
                <div class="box-content">
                    <?= $block->escapeHtml($_order->getBillingAddress()->getFirstname()) ?>,<br/>
                    <?php foreach ($_order->getBillingAddress()->getStreet() as $street): ?>
                        <?= $street ?>,<br/>
                    <?php endforeach;?>
                    <?php if($_order->getBillingAddress()->getCity() != ''): ?>
                        <?= $block->escapeHtml($_order->getBillingAddress()->getCity()) ?> -
                    <?php endif; ?>
                    <?= $block->escapeHtml($_order->getBillingAddress()->getPostcode()) ?>, <?= $helper->getCountryByCode($_order->getBillingAddress()->getCountryId())?><br/>
                    <?= $_order->getCustomerEmail()?><br/>
                    <?php if($helperConfig->getConfig('general/telephone_prefix/enable')): ?>
                        <?= $telephonePrefix.'-'.substr($block->escapeHtml($_order->getBillingAddress()->getTelephone()), 2) ?>
                    <?php else: ?>
                        <?= $_order->getBillingAddress()->getTelephone() ?>
                    <?php endif;?>

                </div>
            </div>
        </div>
    </div>
<?php else: ?>
    <div class="block block-order-details-view">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Order Information')) ?></strong>
        </div>
        <div class="block-content">
            <?php if (!$_order->getIsVirtual()) : ?>
                <div class="box box-order-shipping-address">
                    <strong class="box-title"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></strong>
                    <div class="box-content">
                        <?= $block->escapeHtml($_order->getShippingAddress()->getFirstname()) ?> <?= $block->escapeHtml($_order->getBillingAddress()->getLastname()) ?>,<br/>
                        <?= $block->escapeHtml($_order->getShippingAddress()->getStreet()[0]) ?>,<br/>
                        <?= $block->escapeHtml($_order->getShippingAddress()->getCity()) ?> - <?= $block->escapeHtml($_order->getShippingAddress()->getPostcode()) ?>,<br/>
                        <?= $_order->getCustomerEmail()?><br/>
                        <?php if($helperConfig->getConfig('general/telephone_prefix/enable')): ?>
                            <?= $telephonePrefix.'-'.substr($block->escapeHtml($_order->getShippingAddress()->getTelephone()), 2) ?>
                        <?php else: ?>
                            <?= $block->escapeHtml($_order->getShippingAddress()->getTelephone()) ?>
                        <?php endif;?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="box box-order-billing-address">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Billing Address')) ?></span>
                </strong>
                <div class="box-content">
                    <?= $block->escapeHtml($_order->getBillingAddress()->getFirstname()) ?> <?= $block->escapeHtml($_order->getBillingAddress()->getLastname()) ?>,<br/>
                    <?= $block->escapeHtml($_order->getBillingAddress()->getStreet()[0]) ?>,<br/>
                    <?= $block->escapeHtml($_order->getBillingAddress()->getCity()) ?> - <?= $block->escapeHtml($_order->getBillingAddress()->getPostcode()) ?>,<br/>
                    <?= $_order->getCustomerEmail()?><br/>
                    <?php if($helperConfig->getConfig('general/telephone_prefix/enable')): ?>
                        <?= $telephonePrefix.'-'.substr($block->escapeHtml($_order->getBillingAddress()->getTelephone()), 2) ?>
                    <?php else: ?>
                        <?= $block->escapeHtml($_order->getBillingAddress()->getTelephone()) ?>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>
