<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/** @var \Magento\Customer\Block\Widget\Dob $block */

/*
<?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
   ->setDate($block->getCustomer()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob')
   ->setDate($block->getCustomer()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css. Alternatively we could calculate widths
automatically using block input parameters.
*/

/*$niceApiBlock = $block->getLayout()->createBlock(OnitsukaTigerKorea\NiceApiIntegration\Block\Customer\Account\Create::class);
$niceApiResponse = $niceApiBlock->getNiceApiResponse();
$isModuleEnable = $niceApiBlock->IsModuleEnabled();*/
$linkBlock = $block->getLayout()->createBlock(Seoulwebdesign\KakaoSync\Block\Customer\Link::class);
$linkStatus = $linkBlock->getLinkStatus();

/** @var \Magento\Customer\Model\Session $customerSession */
$isKakaoLogin = 0;
$customerSession = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Customer\Model\Session::class);
if ($customerSession->isLoggedIn()) {
    $customer = $customerSession->getCustomer();
    if ($customer && $customer->getId()) {
        $isKakaoLogin = $customer->getIsKakaoLogin();
    }
}

$fieldCssClass = 'field date field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?= $block->escapeHtmlAttr($fieldCssClass) ?>">
    <label class="label" for="<?= /* @noEscape */ $block->getHtmlId() ?>"><span><?= $block->escapeHtml($block->getStoreLabel('dob')) ?></span></label>
    <div class="control customer-dob my-account-dob">
        <?php if($block->getDob() && (isset($linkStatus['id']))) {?>
            <input type="text" name="dob" id="dob" value="<?= $block->getDob() ?>" class="" style="pointer-events: none;background-color: #f5f5f5;color: #888;border: 1px solid #ccc;" />
        <?php } else { ?>
            <?= $block->getFieldHtml() ?>
        <?php } ?>
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
            <div class="note"><?= $block->escapeHtml($_message) ?></div>
        <?php endif; ?>
        <div class="validation-age hidden mage-error" generated="true">
            <span><?= __('You must be at least fourteen (14) years of age to subscribe.')?></span>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
           "Magento_Customer/js/validation": {}
       }
    }
</script>
<script type="text/javascript">
    require(['jquery', 'domReady!'], function ($) {
        var dataForm = $('#form-validate');
        dataForm.find('.validation-age').hide();
        $('.form-create-account button.submit, .form-edit-account button.save').on("click", function (e) {
            var dateCustomer = $('.customer-dob #dob').val();
            var today = new Date();
            var birthDate = new Date(dateCustomer);
            var age = today.getFullYear() - birthDate.getFullYear();
            var m = today.getMonth() - birthDate.getMonth();
            if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
                age--;
            }
            if (age < 14) {
                dataForm.find('.validation-age').show();
                return false;
            } else {
                dataForm.find('.validation-age').hide();
            }
        })
    });
</script>
