<?php
/** @var \OnitsukaTiger\Ninja\Model\Order $order */
$order = $block->getOrder();
/** @var \Magento\Sales\Api\Data\Shipment $shipment */
$shipment = $block->getShipment();

$histories = $block->getHistories();
?>
<script>
    require(
        [
            'jquery',
            'accordion'
        ], function ($) {
            $(".json").accordion();
            $(".switch").on("click", function (e) {
                $(this).next("div").toggle();
            });
        }
    );
</script>
<style>
.switch {
    box-shadow:inset 0px 1px 0px 0px #ffffff;
    background:linear-gradient(to bottom, #f9f9f9 5%, #e9e9e9 100%);
    background-color:#f9f9f9;
    border-radius:4px;
    border:1px solid #dcdcdc;
    display:inline-block;
    cursor:pointer;
    color:#666666;
    font-family:Arial;
    font-size:10px;
    font-weight:bold;
    padding:4px 8px;
    text-decoration:none;
    text-shadow:0px 1px 0px #ffffff;
}
.switch:hover {
    background:linear-gradient(to bottom, #e9e9e9 5%, #f9f9f9 100%);
    background-color:#e9e9e9;
}
.switch:active {
    position:relative;
    top:1px;
}

.content {
    padding: 8px;
    margin: 2px 0;
    background: #eeeeee;
    border-radius: 6px;
}
</style>
<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo $order->getTrackingId(); ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
            <tr>
                <th><?php echo __('Order') . ':' ?></th>
                <td><?php echo $shipment->getOrder()->getIncrementId(); ?> </td>
            </tr>
            <tr>
                <th><?php echo __('Shipment') . ':' ?></th>
                <td><?php echo $shipment->getIncrementId(); ?> </td>
            </tr>
            <tr>
                <th><?php echo __('Data') . ':' ?></th>
                <td><?php echo $order->getJson() ?></td>
            </tr>
        </tbody>
    </table>

    <div class="fieldset-wrapper-title">
        <span class="title">Status</span>
    </div>
    <?php if (count($histories)): ?>
        <div class="dashboard-item-content">
            <table class="admin__table-primary dashboard-data">
                <thead>
                <tr>
                    <th><?php echo __('#') ?></th>
                    <th><?php echo __('Date') ?></th>
                    <th><?php echo __('Status') ?></th>
                    <th><?php echo __('Data') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($histories as $id => $value): ?>
                    <tr>
                        <td width="5%"><?php echo $id ?></td>
                        <td width="10%"><?php echo $value['created_at'] ?></td>
                        <td width="10%"><?php echo $value['status'] ?></td>
                        <td class="json">
                            <div class="switch">show data</div>
                            <div class="content" style="display:none"><?php echo $value['json'] ?></div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="clear"></div>
    <?php endif; ?>

</div>
