<?php
/**
 * @var $block \Magento\CatalogSearch\Block\Result
 */
/** @var \Vaimo\OTAdobeDataLayer\Helper\Data $helper */
$helper = $this->helper('Vaimo\OTAdobeDataLayer\Helper\Data');

/** @var $block \Vaimo\OTAdobeDataLayer\Block\Track\Cart */
?>
<?php if($helper->isEnabledAdobeLaunch()): ?>
    <?php
        $pageInfo = json_decode($helper->getPageInfo());
        $pageInfo = json_encode($pageInfo->pageInfo);
        $userInfo = json_encode($helper->getUserInfo());
    ?>
    <?php
        $cartItems = $block->pushViewCartEvent();
    ?>
    <script>
        require(['jquery', 'mage/cookies'], function($){
            // custom code for add adobe data layer start
            $(document).ready(function() {
                let adobeDataLayer = window.adobeDataLayer ? window.adobeDataLayer : [];

                adobeDataLayer.push(
                    {
                        'event' : 'cartView',
                        'page' : {
                                'pageInfo' : JSON.parse('<?= $pageInfo ?>')
                            },
                        'userInfo' : JSON.parse('<?= $userInfo ?>'),
                        'productListItems' : JSON.parse('<?= $cartItems; ?>')
                    }
                ); //push data in to Adobe data layer

                window.adobeDataLayer = adobeDataLayer;
            });
            // custom code for add adobe data layer end
        });
    </script>
<?php endif;?>