<?php
$helper = $this->helper(\OnitsukaTiger\Customer\Helper\Data::class);
$helperConfig = $this->helper(\OnitsukaTiger\Fixture\Helper\Data::class);
$telephonePrefix = $helperConfig->getConfig('general/telephone_prefix/number') ? $helperConfig->getConfig('general/telephone_prefix/number') : '66';
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order) : ?>
    <p class="title-address"><?= __('Shipping Address')?></p>
    <?= $_order->getShippingAddress()->getFirstName()?><br/>
    <?php foreach ($_order->getShippingAddress()->getStreet() as $street): ?>
        <?= $street ?>,<br/>
    <?php endforeach;?>
    <?php if($_order->getShippingAddress()->getCity() != ''): ?>
        <?= $block->escapeHtml($_order->getShippingAddress()->getCity()) ?><br/>
    <?php endif; ?>
    <?= $helper->getCountryByCode($_order->getShippingAddress()->getCountryId())?><br/>
    <?= __('Postal Code:')?> <?= $_order->getShippingAddress()->getPostcode()?>,<br/>
    <?php if($helperConfig->getConfig('general/telephone_prefix/enable')): ?>
        <?= __('Mobile:')?> <?= $telephonePrefix.'-'.substr($block->escapeHtml($_order->getShippingAddress()->getTelephone()), 2) ?>
    <?php else: ?>
        <?= __('Mobile:')?> <?= $_order->getShippingAddress()->getTelephone() ?>
    <?php endif;?>
    <br/>
    <?= __('Email:')?><?= $_order->getShippingAddress()->getEmail()?>
<?php endif; ?>
