<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
//phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
?>
<?php /** @var $block \OnitsukaTiger\NetSuiteStoreShipping\Block\Adminhtml\Shipment\Pos\View */ ?>
<div class="admin__control-table-wrapper">
    <form id="pos-shipping-form" data-mage-init='{"validation": {}}'>
        <table class="data-table admin__control-table" id="shipment_pos">
            <?php if ($block->getPosReceiptNumber()) : ?>
            <tbody>
            <tr class="odd">
                <td class="col-number">
                    <?= $block->escapeHtml($block->getPosReceiptNumber()) ?>
                </td>
                <td class="col-delete last"><button class="action-delete" type="button" onclick="deletePosReceiptNumber('<?= $block->escapeJs($block->escapeUrl($block->getRemoveUrl())) ?>'); return false;"><span><?= $block->escapeHtml(__('Delete')) ?></span></button></td>
            </tr>
            </tbody>
            <?php else : ?>
            <tfoot>
            <tr>
                <td class="col-number">
                    <input class="input-text validate-length maximum-length-100 admin__control-text required-entry"
                           type="text"
                           id="pos_number"
                           name="number"
                           value="" />
                </td>
                <td class="col-delete last"><?= $block->getSaveButtonHtml() ?></td>
            </tr>
            </tfoot>
            <?php endif; ?>
        </table>
    </form>
</div>

<script>
    require(['prototype', 'jquery', 'Magento_Ui/js/modal/confirm'], function(prototype, $j, confirm) {
//<![CDATA[
        function savePosReceiptInfo(node, url) {
            var form = $j('#pos-shipping-form');

            if (form.validation() && form.validation('isValid')) {
                submitAndReloadArea(node, url);
            }
        }

        function deletePosReceiptNumber(url) {
            confirm({
                content: '<?= $block->escapeJs($block->escapeHtml(__('Are you sure?'))) ?>',
                actions: {
                    /**
                     * Confirm action.
                     */
                    confirm: function () {
                        submitAndReloadArea($('shipment_pos').parentNode, url);
                    }
                }
            });
        }

        window.deletePosReceiptNumber = deletePosReceiptNumber;
        window.savePosReceiptInfo = savePosReceiptInfo;
//]]>

    });
</script>
