<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Search\ViewModel\ConfigProvider $configProvider */
$configProvider = $block->getData('configProvider');
$helper = $configProvider->getSearchHelperData();
$niceApiBlock = $block->getLayout()->createBlock(\OnitsukaTigerKorea\Search\Block\Search::class);
$productList = $niceApiBlock->getRotatingProducts();
$productJson = json_encode($productList);
$searchHelper = $this->helper(\OnitsukaTigerKorea\Search\Helper\Data::class);
$isEnabled = $searchHelper->isEnabled();
if (!$isEnabled) {
    ?>
    <div class="block block-search">
        <div class="block block-title"><strong><?= $escaper->escapeHtml(__('Search')) ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                               type="text"
                               name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                               value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                               placeholder="<?= $escaper->escapeHtmlAttr(__('SEARCH...')) ?>"
                               class="input-text"
                               maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"
                               aria-expanded="false"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?= $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?= $escaper->escapeHtml(__('Search')) ?>"
                            class="action search"
                            aria-label="Search"
                    >
                        <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
<?php } else { ?>
    <div class="block block-search">
        <script type="text/javascript">
            require([
                'jquery',
                'Magento_Theme/js/swiper-bundle'
            ], function($, Swiper){
                var swiper = new Swiper('.swiper-container.search-sku-bar-swiper', {
                    direction: 'vertical',
                    slidesPerView: 1,
                    grabCursor: true,
                    loop: true,
                    autoplay: {
                        delay: 1200,
                    },
                });
            });
        </script>

        <div class="search-sku-bar swiper-container search-sku-bar-swiper">
            <div class="swiper-wrapper">
                <?php foreach ($productList as $product): ?>
                    <div class="swiper-slide">
                        <?= $escaper->escapeHtml($product['name']) ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="block block-content">
            <span class="search-popup-input">Search</span>
        </div>
    </div>

    <script type="text/javascript">
        require(['jquery', 'Magento_Theme/js/swiper-bundle'], function ($, Swiper) {
            var swiperInstance;
            var swiperInitialized = false;

            function initSwiper() {
                if (swiperInstance) {
                    swiperInstance.destroy(true, true);
                }

                swiperInstance = new Swiper('.search-sku-bar.swiper-container.search-sku-bar-swiper-mobile', {
                    direction: 'vertical',
                    slidesPerView: 1,
                    grabCursor: true,
                    loop: true,
                    autoplay: {
                        delay: 1200,
                    },
                });
            }

            $(document).ready(function () {
                $(".search-popup-input, .search-button").click(function () {
                    $('body').addClass('search-bar-active');
                });

                $(".popup-search .popup-search-button").click(function () {
                    $('body').removeClass('search-bar-active').addClass('search-bar-inactive');
                });

                $(".page-header-block-search .search-button").click(function () {
                    const $swiperBar = $(".search-sku-bar.swiper-container.search-sku-bar-swiper-mobile");
                    const $input = $(".input-text.myInput");

                    if ($(this).hasClass('search-bar-close')) {
                        $(this).removeClass('search-bar-close');
                        $('body').removeClass('search-bar-active search-bar-inactive');
                        $('.header-alert .slider-content').slick('refresh');
                    } else {
                        $(this).addClass('search-bar-close');

                        if (!swiperInitialized && window.innerWidth < 768) {
                            initSwiper();
                            swiperInitialized = true;
                        }

                        if (window.innerWidth < 768) {
                            if ($swiperBar.find('.swiper-slide').length === 0) {
                                $swiperBar.hide();
                                $input.attr("placeholder", "검색");
                            } else {
                                $swiperBar.show();
                                $input.removeAttr("placeholder");
                            }
                        }
                        if ($('.input-text.myInput').val().trim().length > 0) {
                            $swiperBar.hide();
                        } else {
                            $swiperBar.show();
                        }
                    }
                });

                $(".input-text.myInput, .swiper-wrapper").on('focus touchstart', function () {
                    $(".search-sku-bar.swiper-container.search-sku-bar-swiper-mobile").hide();
                    $(this).attr("placeholder", "검색");
                });
            });

        });
    </script>

<?php } ?>
