<?php
/** @var \OnitsukaTiger\Reindex\Block\Adminhtml\System\Config\Reindex $block */
?>

<?= /** @noEscape */ $block->getButtonHtml() ?>
<span class="collect-indicator" id="collect_span">
    <span class="processing" hidden="hidden">
        <img alt="Collecting" style="margin:0 5px"
             src="<?= /** @noEscape */ $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
        <?= /** @noEscape */ __('Please wait ...') ?>
    </span>
    <img class="collected" alt="Collected" style="margin:-3px 5px"
         src="<?= /** @noEscape */ $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
</span>

<script>
    require([
        'jquery',
        'prototype'
    ], function ($) {
        var collectSpan = $('#collect_span');
        var buttonDownload = $('#reindex_button');
        buttonDownload.on("click", function (e) {
            var params = {};
            new Ajax.Request('<?= /** @noEscape */ $block->getAjaxUrl() ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    $('#collect_message_span').text('');
                    $('#row_product_ot_reindex_run .message.message-error').remove();
                    $('#row_product_ot_reindex_run .message.message-success').remove();
                    buttonDownload.prop("disabled", true);
                },
                onSuccess: function (response) {
                    var response = JSON.parse(response.responseText);
                    collectSpan.find('.processing').hide();
                    collectSpan.find('.collected').show();
                    buttonDownload.prop("disabled", false);
                    if (response.success) {
                        $('<div class="message message-success" style="margin-bottom: 5px;color:#79a22e"><p>' + response.message + '</p></div>').insertBefore(buttonDownload);
                    } else {
                        $('<div class="message message-error" style="margin-bottom: 5px;color:red"><p>' + response.message + '</p></div>').insertBefore(buttonDownload);
                    }
                },
                always: function () {
                    buttonDownload.prop("disabled", false);
                }
            });
        });
    });
</script>
