<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
?>
<?php if($store->getCode() == 'web_vn_vi') { ?>
    <?= $block->escapeHtml(__("Bạn phải xác nhận tài khoản của mình. Vui lòng kiểm tra email của bạn để nhận đường link hoặc <a href='%1'>nhấp vào đây</a> để yêu cầu một đường link mới.", $block->getData('url')), ['a']); ?>
<?php } else { ?>
    <?= $block->escapeHtml(__("You must confirm your account. Please check your email for the confirmation link or <a href='%1'>click here</a> for a new link.", $block->getData('url')), ['a']); ?>
<?php } ?>
