<?php
/** @var \Seoulwebdesign\KakaoSync\Block\Login $block */
?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $escaper->escapeHtml(__('Login with Kakao')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <div class="actions-toolbar">
            <div class="primary">
                <a id="custom-login-btn" href="javascript:loginWithKakao()">
                    <img
                        src="//k.kakaocdn.net/14/dn/btroDszwNrM/I6efHub1SN5KCJqLm1Ovx1/o.jpg"
                        alt="Kakao Login button"
                    />
                </a>
            </div>
        </div>
    </div>
</div>
