<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
$invoice = $block->getInvoice();
$order = $invoice->getOrder();
$subtotalIncludeTax = $order->formatPrice($invoice->getSubtotalInclTax());

$helperFixture = $this->helper(\OnitsukaTiger\Fixture\Helper\Data::class);
$totalInclusiveTax = $helperFixture->getConfig('tax/cart_display/subtotal');
if ($totalInclusiveTax == 1){
    $totalIncludeLabel = 'Exclusive';
}else{
    $totalIncludeLabel = 'Inclusive';
}
?>
<div class="col-10 text-right">
    <?= $block->escapeHtml(__('Subtotal ('. $totalIncludeLabel .' of GST)')) ?>
</div>
<div class="col-2 text-right">
    <?= /* @noEscape */ $subtotalIncludeTax ?>
</div>
