<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php $_order = $block->getOrder() ?>
<?php $helper = $this->helper(\OnitsukaTiger\Sales\Helper\Data::class)?>
<?php $helperStore = $this->helper(\OnitsukaTiger\Store\Helper\Data::class)?>
<?php
$orderStatus = $this->getData('order_status') ?? $_order->getStatus();
if(strtolower($orderStatus) == 'pre_order_processing' ){
    $orderStatus = 'Pre-order Processing';
}elseif(strtolower($orderStatus) == 'processing' && $_order->getIsPreOrder()){
    if($helperStore->getStoreCode($_order->getStoreId()) == 'web_sg_en' || $helperStore->getStoreCode($_order->getStoreId()) == 'web_id_en' || $helperStore->getStoreCode($_order->getStoreId()) == 'web_my_en'|| $helperStore->getStoreCode($_order->getStoreId()) == 'web_th_en'){
        $orderStatus = 'Pre-order Processing';
    }elseif ($helperStore->getStoreCode($_order->getStoreId()) == 'web_th_th'){
        $orderStatus = 'การประมวลผลการสั่งซื้อล่วงหน้า';
    }
}else{
    $orderStatus =  ucwords($orderStatus);
}
?>
<?php if ($_order) : ?>
    <?php $date = date("d-M-Y", strtotime($_order->getCreatedAt()));?>
    <p><strong><?= __('Order Number:')?></strong> <?= $_order->getIncrementId()?></p>
    <p><strong><?= __('Order Date:')?></strong> <?= $date?></p>
    <p><strong><?= __('Order Total:')?></strong> <?= $block->getOrder()->formatPrice($_order->getGrandTotal())?></p>
    <p><strong><?= __('Shipping & Handling:')?></strong> <?= $block->getOrder()->formatPrice($_order->getShippingAmount())?></p>
    <p><strong><?= __('Promotion Discount:')?></strong> <?= $block->getOrder()->formatPrice($_order->getDiscountAmount())?></p>
    <p><strong><?= __('Order Method:')?></strong> <?= __('Home Delivery')?></p>
    <p><strong><?= __('Order Status:')?></strong> <span><?= __($orderStatus); ?></span></p>
<?php endif; ?>
