<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Edit $block */
?>
<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
<?php
$helper = $this->helper(\OnitsukaTiger\Customer\Helper\Data::class);
$addressType = 0;
$lengthOfPostcode = $this->helper(\OnitsukaTiger\Fixture\Helper\Data::class)->getConfig('customer/address/length_of_postcode') ?? 5;
$helperFixture = $this->helper(\OnitsukaTiger\Fixture\Helper\Data::class);
?>
<form data-bind="scope:'addressPopup'" class="form-address-edit form-address-edit-popup"
      action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
    <fieldset class="fieldset">
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <input type="hidden" id="id" name="id" value="">
        <input type="hidden" id="isAjax" name="isAjax" value="1">
        <?= $block->getNameBlockHtml() ?>


        <?php if ($_telephone->isEnabled()) : ?>
            <?= $_telephone->setTelephone('')->toHtml() ?>
        <?php endif ?>
        <?php $_streetValidationClass = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label">
                <span><?= /* @noEscape */ __('Address') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="street[]"
                       value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= /* @noEscape */ __('Address') ?>"
                       id="street_1"
                       data-character="<?= $helperFixture->getConfig('customer_address_validate/general/enable_validation_character') ?>"
                       class="<?php if($helperFixture->getConfig('customer_address_validate/general/enable_validation_character')): ?>validate-character-address <?php endif;?>  <?php if(!$helperFixture->getConfig('customer_address_validate/general/enable_limitations')): ?>validate-length maximum-length-150 <?php endif;?>xml-characters-validate input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"/>
            </div>
        </div>
        <div class="field street">
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 1, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i < $_n; $_i++) : ?>
                <label class="label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                    <span><?= $block->escapeHtml(__('Address %1', $_i + 1)) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="street[<?= /* @noEscape */ $_i + 1 ?>]"
                           value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Address %1', $_i + 1)) ?>"
                           id="street_<?= /* @noEscape */ $_i + 1 ?>"
                           data-character="<?= $helperFixture->getConfig('customer_address_validate/general/enable_validation_character') ?>"
                           class="<?php if($helperFixture->getConfig('customer_address_validate/general/enable_validation_character')): ?>validate-character-address <?php endif;?> <?php if(!$helperFixture->getConfig('customer_address_validate/general/enable_limitations')): ?>validate-length maximum-length-150 <?php endif;?> xml-characters-validate input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                </div>
            <?php endfor; ?>
        </div>
        <?php if($helperFixture->getConfig('customer_address_validate/general/enable_limitations')): ?>
            <?php $addressMaxLength = $helperFixture->getConfig('customer_address_validate/general/limitations_character') ? $helperFixture->getConfig('customer_address_validate/general/limitations_character') : '81';?>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php $addressValue = $block->getStreetLine(1); ?>
            <?php for ($_i = 1, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i < $_n; $_i++) : ?>
                <?php $addressValue = $addressValue.' '.$block->getStreetLine($_i + 1)?>
            <?php endfor; ?>
            <div class="field validattion-address">
                <label class="label" for="customer-validations-street">
                </label>
                <div class="control">
                    <input type="text"
                           id="customer-validations-street"
                           name="customer-validations-street"
                           value="<?= $block->escapeHtmlAttr($addressValue) ?>"
                           class="input-text  validate-character-length maximum-character-length-<?= $addressMaxLength?> "/>
                </div>
            </div>
        <?php endif; ?>
        <div class="field zip required">
            <label class="label" for="zip">
                <span><?= /* @noEscape */ __('Postal code') ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<?= $block->escapeHtmlAttr('') ?>"
                       title="<?= /* @noEscape */ __('Postal code') ?>"
                       id="zip"
                       maxlength="<?= $lengthOfPostcode?>"
                       class="validate-length minimum-length-<?= $lengthOfPostcode?> maximum-length-<?= $lengthOfPostcode?> validate-number validate-digits input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
                <div role="alert" class="message warning" style="display:none">
                    <span></span>
                </div>
            </div>
        </div>
        <div class="field country required">
            <label class="label" for="country"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id">
                <span><?= /* @noEscape */ __('Province') ?></span>
            </label>
            <div class="control">
                <select id="region_id" name="region_id"
                        title="<?= /* @noEscape */ __('Province') ?>"
                        class="validate-select region_id" <?= /* @noEscape */ !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>>
                    <option value=""><?= $block->escapeHtml(__('-- --Select State-- --')) ?></option>
                </select>
                <input type="text"
                       id="region"
                       name="region"
                       value="Vietnam"
                       title="<?= /* @noEscape */ __('Province') ?>"
                       class="phone-countrycode input-text required-entry validate-not-number-first <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>"<?= !$block->getConfig('general/region/display_all') ? ' disabled="disabled"' : '' ?>/>
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
            <div class="control">
                <input type="text"
                       name="city"
                       value="Vietnam"
                       title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                       class="phone-countrycode input-text required-entry <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>"
                       id="city">
            </div>
        </div>
        <input type="hidden" name="default_billing" value="1" />
        <input type="hidden" name="default_shipping" value="1">
    </fieldset>
    <div class="required_fields_txt"><?= __('* Required Fields')?></div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {
                "postCodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
    },
    "addressValidationCharacter": {
        "fieldClass":".street",
        "fieldValidateClass":".validattion-address"
    },
    "xmlCharactersValidate":{
    }
},
"#country": {
    "regionUpdater": {
        "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
    }
}
}
</script>
